import json

# 新增的privacy key（中文值）
new_keys_zh = {
    "privacy.updated": "最后更新：2026年6月2日",
    "privacy.s1.h2": "1.1 所有用户（免费用户 + PRO会员）",
    "privacy.s1.li1": "IP地址（匿名化处理，仅保留前两个字节用于地理位置判断）",
    "privacy.s1.li3": "页面访问记录（访问了哪些页面、停留时间）",
    "privacy.s1.li4": "必要Cookie：用于确保网站基本功能正常运行（如维持会话状态）",
    "privacy.s1.h3": "1.2 PRO会员用户（额外收集）",
    "privacy.s1.li5": "邮箱地址：用于身份验证、保障申请处理和服务通知",
    "privacy.s1.li6": "API调用时间戳：用于配额管理和服务优化",
    "privacy.s1.li7": "时区偏好设置：用于个性化时间显示",
    "privacy.s1.li8": "NTP校准状态查询记录：用于可信度评估和改进",
    "privacy.s1.h4": "1.3 我们明确不收集的数据",
    "privacy.s2.p2": "我们不会将您的数据用于：精准广告投放、用户画像构建、出售给第三方。",
    "privacy.s5.li1": "访问权：要求查阅我们持有的您的个人数据",
    "privacy.s5.li2": "更正权：要求更正不准确或不完整的数据",
    "privacy.s5.li3": "导出权：要求以结构化、通用格式导出您的数据",
    "privacy.s5.li4": "删除权：要求删除我们持有的您的个人数据",
    "privacy.s5.p2": "如需行使上述任何权利，请发送邮件至 privacy@globetimezone.com。我们将在30天内响应您的请求。",
    "privacy.s6.p1": "我们仅使用必要的Cookie来确保网站基本功能正常运行（如记住您的语言偏好）。我们不使用任何跟踪Cookie、第三方广告Cookie或分析Cookie。您可以通过浏览器设置完全禁用Cookie，但这可能会影响网站的某些功能（如偏好记忆）。",
    "privacy.s8.p3": "邮箱：privacy@globetimezone.com",
    "privacy.footer.terms": "服务条款",
    "privacy.footer.privacy": "隐私政策",
    "privacy.footer.trust": "可信度保障",
}

translations = {
    "en": {
        "privacy.updated": "Last updated: June 2, 2026",
        "privacy.s1.h2": "1.1 All Users (Free + PRO Members)",
        "privacy.s1.li1": "IP address (anonymized, only the first two bytes retained for geolocation)",
        "privacy.s1.li3": "Page visit records (which pages visited, time spent)",
        "privacy.s1.li4": "Essential Cookies: to ensure basic website functionality (e.g., maintaining session state)",
        "privacy.s1.h3": "1.2 PRO Members (Additional Collection)",
        "privacy.s1.li5": "Email address: for identity verification, guarantee request processing, and service notifications",
        "privacy.s1.li6": "API call timestamps: for quota management and service optimization",
        "privacy.s1.li7": "Timezone preference settings: for personalized time display",
        "privacy.s1.li8": "NTP calibration status query records: for trust assessment and improvement",
        "privacy.s1.h4": "1.3 Data We Explicitly Do NOT Collect",
        "privacy.s2.p2": "We will NOT use your data for: targeted advertising, user profiling, or selling to third parties.",
        "privacy.s5.li1": "Right of Access: request to view your personal data we hold",
        "privacy.s5.li2": "Right to Rectification: request correction of inaccurate or incomplete data",
        "privacy.s5.li3": "Right to Portability: request your data in a structured, common format",
        "privacy.s5.li4": "Right to Erasure: request deletion of your personal data we hold",
        "privacy.s5.p2": "To exercise any of the above rights, please email privacy@globetimezone.com. We will respond within 30 days.",
        "privacy.s6.p1": "We only use essential Cookies to ensure basic website functionality (e.g., remembering your language preference). We do NOT use any tracking cookies, third-party advertising cookies, or analytics cookies. You can fully disable cookies via browser settings, but this may affect certain features.",
        "privacy.s8.p3": "Email: privacy@globetimezone.com",
        "privacy.footer.terms": "Terms of Service",
        "privacy.footer.privacy": "Privacy Policy",
        "privacy.footer.trust": "Trust Guarantee",
    },
    "de": {
        "privacy.updated": "Zuletzt aktualisiert: 2. Juni 2026",
        "privacy.s1.h2": "1.1 Alle Nutzer (Kostenlos + PRO-Mitglieder)",
        "privacy.s1.li1": "IP-Adresse (anonymisiert, nur die ersten zwei Bytes fuer Geolokalisierung)",
        "privacy.s1.li3": "Seitenbesuchsaufzeichnungen (welche Seiten besucht, Verweildauer)",
        "privacy.s1.li4": "Notwendige Cookies: zur Sicherstellung der grundlegenden Website-Funktionalitaet",
        "privacy.s1.h3": "1.2 PRO-Mitglieder (Zusaetzliche Erfassung)",
        "privacy.s1.li5": "E-Mail-Adresse: fuer Identitaetspruefung, Garantieanfragen und Service-Benachrichtigungen",
        "privacy.s1.li6": "API-Aufruf-Zeitstempel: fuer Kontingentmanagement und Service-Optimierung",
        "privacy.s1.li7": "Zeitzonen-Einstellungen: fuer personalisierte Zeitanzeige",
        "privacy.s1.li8": "NTP-Kalibrierungsstatus-Abfrageprotokolle: fuer Vertrauensbewertung und Verbesserung",
        "privacy.s1.h4": "1.3 Daten, die wir NICHT sammeln",
        "privacy.s2.p2": "Wir verwenden Ihre Daten NICHT fuer: zielgerichtete Werbung, Nutzerprofilierung oder Verkauf an Dritte.",
        "privacy.s5.li1": "Auskunftsrecht: Einsicht in Ihre personenbezogenen Daten",
        "privacy.s5.li2": "Recht auf Berichtigung: Korrektur ungenauer Daten",
        "privacy.s5.li3": "Recht auf Datenuebertragbarkeit: Ihre Daten in strukturiertem Format",
        "privacy.s5.li4": "Recht auf Loeschung: Loeschung Ihrer personenbezogenen Daten",
        "privacy.s5.p2": "Um Rechte auszuueben, senden Sie bitte eine E-Mail an privacy@globetimezone.com. Wir antworten innerhalb von 30 Tagen.",
        "privacy.s6.p1": "Wir verwenden nur notwendige Cookies fuer die grundlegende Website-Funktionalitaet. Keine Tracking-, Werbe- oder Analyse-Cookies. Sie koennen Cookies in den Browser-Einstellungen deaktivieren.",
        "privacy.s8.p3": "E-Mail: privacy@globetimezone.com",
        "privacy.footer.terms": "Nutzungsbedingungen",
        "privacy.footer.privacy": "Datenschutzrichtlinie",
        "privacy.footer.trust": "Vertrauensgarantie",
    },
    "fr": {
        "privacy.updated": "Derniere mise a jour : 2 juin 2026",
        "privacy.s1.h2": "1.1 Tous les utilisateurs (Gratuit + Membres PRO)",
        "privacy.s1.li1": "Adresse IP (anonymisee, seuls les deux premiers octets conserves pour la geolocalisation)",
        "privacy.s1.li3": "Enregistrements de visites de pages (quelles pages visitees, temps passe)",
        "privacy.s1.li4": "Cookies essentiels : pour assurer le fonctionnement de base du site",
        "privacy.s1.h3": "1.2 Membres PRO (Collecte supplementaire)",
        "privacy.s1.li5": "Adresse e-mail : pour la verification d identite et les notifications de service",
        "privacy.s1.li6": "Horodatages des appels API : pour la gestion des quotas",
        "privacy.s1.li7": "Preferences de fuseau horaire : pour l affichage personnalise",
        "privacy.s1.li8": "Enregistrements de requetes NTP : pour l evaluation de confiance",
        "privacy.s1.h4": "1.3 Donnees que nous ne collectons PAS",
        "privacy.s2.p2": "Nous n utiliserons PAS vos donnees pour : publicite ciblee, profilage ou vente a des tiers.",
        "privacy.s5.li1": "Droit d acces : consulter vos donnees personnelles",
        "privacy.s5.li2": "Droit de rectification : corriger des donnees inexactes",
        "privacy.s5.li3": "Droit a la portabilite : obtenir vos donnees en format structure",
        "privacy.s5.li4": "Droit a l effacement : supprimer vos donnees personnelles",
        "privacy.s5.p2": "Pour exercer vos droits, envoyez un e-mail a privacy@globetimezone.com. Nous repondrons dans les 30 jours.",
        "privacy.s6.p1": "Nous n utilisons que les cookies essentiels. Pas de cookies de suivi, publicitaires ou d analyse. Vous pouvez les desactiver dans les parametres du navigateur.",
        "privacy.s8.p3": "E-mail : privacy@globetimezone.com",
        "privacy.footer.terms": "Conditions d utilisation",
        "privacy.footer.privacy": "Politique de confidentialite",
        "privacy.footer.trust": "Garantie de confiance",
    },
    "es": {
        "privacy.updated": "Ultima actualizacion: 2 de junio de 2026",
        "privacy.s1.h2": "1.1 Todos los usuarios (Gratis + Miembros PRO)",
        "privacy.s1.li1": "Direccion IP (anonimizada, solo los primeros dos bytes para geolocalizacion)",
        "privacy.s1.li3": "Registros de visitas de paginas (que paginas visitadas, tiempo de permanencia)",
        "privacy.s1.li4": "Cookies esenciales: para garantizar la funcionalidad basica del sitio",
        "privacy.s1.h3": "1.2 Miembros PRO (Recopilacion adicional)",
        "privacy.s1.li5": "Direccion de correo electronico: para verificacion de identidad y notificaciones",
        "privacy.s1.li6": "Marcas de tiempo de llamadas API: para gestion de cuotas",
        "privacy.s1.li7": "Configuracion de zona horaria: para visualizacion personalizada",
        "privacy.s1.li8": "Registros de consultas NTP: para evaluacion de confianza",
        "privacy.s1.h4": "1.3 Datos que NO recopilamos",
        "privacy.s2.p2": "NO usaremos sus datos para: publicidad dirigida, creacion de perfiles o venta a terceros.",
        "privacy.s5.li1": "Derecho de acceso: solicitar ver sus datos personales",
        "privacy.s5.li2": "Derecho de rectificacion: solicitar correccion de datos inexactos",
        "privacy.s5.li3": "Derecho a la portabilidad: solicitar datos en formato estructurado",
        "privacy.s5.li4": "Derecho de supresion: solicitar eliminacion de sus datos",
        "privacy.s5.p2": "Para ejercer sus derechos, envie un correo a privacy@globetimezone.com. Responderemos en 30 dias.",
        "privacy.s6.p1": "Solo usamos cookies esenciales. No usamos cookies de seguimiento, publicitarias o analiticas. Puede deshabilitarlas en la configuracion del navegador.",
        "privacy.s8.p3": "Correo electronico: privacy@globetimezone.com",
        "privacy.footer.terms": "Terminos de servicio",
        "privacy.footer.privacy": "Politica de privacidad",
        "privacy.footer.trust": "Garantia de confianza",
    },
    "ja": {
        "privacy.updated": "最終更新：2026年6月2日",
        "privacy.s1.h2": "1.1 全ユーザー（無料 + PROメンバー）",
        "privacy.s1.li1": "IPアドレス（匿名化処理、最初の2バイトのみ地理位置情報判断に使用）",
        "privacy.s1.li3": "ページ訪問記録（訪問したページ、滞在時間）",
        "privacy.s1.li4": "必須Cookie：ウェブサイトの基本機能を確保するため（例：セッション状態の維持）",
        "privacy.s1.h3": "1.2 PROメンバー（追加収集）",
        "privacy.s1.li5": "メールアドレス：身元確認、保証申請処理、サービス通知のため",
        "privacy.s1.li6": "API呼び出しタイムスタンプ：クォータ管理とサービス最適化のため",
        "privacy.s1.li7": "タイムゾーン設定：個人化された時間表示のため",
        "privacy.s1.li8": "NTP校正ステータスクエリ記録：信頼性評価と改善のため",
        "privacy.s1.h4": "1.3 収集しないデータ",
        "privacy.s2.p2": "お客様のデータを以下の目的には使用しません：ターゲット広告配信、ユーザープロファイリング、第三者への販売。",
        "privacy.s5.li1": "アクセス権：当社が保有するお客様の個人データの閲覧を要求する",
        "privacy.s5.li2": "訂正権：不正確または不完全なデータの修正を要求する",
        "privacy.s5.li3": "可搬性の権利：構造化された一般的な形式でデータを要求する",
        "privacy.s5.li4": "削除権：当社が保有するお客様の個人データの削除を要求する",
        "privacy.s5.p2": "上記のいずれかの権利を行使するには、privacy@globetimezone.comにメールをお送りください。30日以内に対応いたします。",
        "privacy.s6.p1": "ウェブサイトの基本機能を確保するために必要なCookieのみを使用します（例：言語設定の記憶）。トラッキングCookie、第三者広告Cookie、分析Cookieは使用しません。",
        "privacy.s8.p3": "メール：privacy@globetimezone.com",
        "privacy.footer.terms": "利用規約",
        "privacy.footer.privacy": "プライバシーポリシー",
        "privacy.footer.trust": "信頼保証",
    },
    "ko": {
        "privacy.updated": "최종 업데이트: 2026년 6월 2일",
        "privacy.s1.h2": "1.1 모든 사용자(무료 + PRO 회원)",
        "privacy.s1.li1": "IP 주소(익명화 처리, 지리적 위치 판단에 앞 두 바이트만 보유)",
        "privacy.s1.li3": "페이지 방문 기록(방문한 페이지, 체류 시간)",
        "privacy.s1.li4": "필수 쿠키: 웹사이트 기본 기능 보장(예: 세션 상태 유지)",
        "privacy.s1.h3": "1.2 PRO 회원(추가 수집)",
        "privacy.s1.li5": "이메일 주소: 신원 확인, 보증 요청 처리 및 서비스 알림용",
        "privacy.s1.li6": "API 호출 타임스탬프: 할당량 관리 및 서비스 최적화용",
        "privacy.s1.li7": "시간대 기본 설정: 개인화된 시간 표시용",
        "privacy.s1.li8": "NTP 교정 상태 쿼리 기록: 신뢰도 평가 및 개선용",
        "privacy.s1.h4": "1.3 수집하지 않는 데이터",
        "privacy.s2.p2": "귀하의 데이터를 다음 목적으로 사용하지 않습니다: 타겟 광고, 사용자 프로파일링, 제3자 판매.",
        "privacy.s5.li1": "열람권: 당사가 보유한 귀하의 개인 데이터 열람 요청",
        "privacy.s5.li2": "정정권: 부정확하거나 불완전한 데이터 수정 요청",
        "privacy.s5.li3": "이동성 권리: 구조화된 일반적인 형식으로 데이터 요청",
        "privacy.s5.li4": "삭제권: 당사가 보유한 귀하의 개인 데이터 삭제 요청",
        "privacy.s5.p2": "위 권리 중 하나를 행사하려면 privacy@globetimezone.com으로 이메일을 보내주세요. 30일 이내에 답변하겠습니다.",
        "privacy.s6.p1": "웹사이트 기본 기능 보장을 위한 필수 쿠키만 사용합니다. 추적 쿠키, 제3자 광고 쿠키 또는 분석 쿠키는 사용하지 않습니다.",
        "privacy.s8.p3": "이메일: privacy@globetimezone.com",
        "privacy.footer.terms": "이용 약관",
        "privacy.footer.privacy": "개인정보 처리방침",
        "privacy.footer.trust": "신뢰 보장",
    },
    "pt": {
        "privacy.updated": "Ultima atualizacao: 2 de junho de 2026",
        "privacy.s1.h2": "1.1 Todos os usuarios (Gratuito + Membros PRO)",
        "privacy.s1.li1": "Endereco IP (anonimizado, apenas os dois primeiros bytes retidos para geolocalizacao)",
        "privacy.s1.li3": "Registros de visitas de paginas (quais paginas visitadas, tempo de permanencia)",
        "privacy.s1.li4": "Cookies essenciais: para garantir a funcionalidade basica do site",
        "privacy.s1.h3": "1.2 Membros PRO (Coleta adicional)",
        "privacy.s1.li5": "Endereco de e-mail: para verificacao de identidade e notificacoes de servico",
        "privacy.s1.li6": "Timestamps de chamadas de API: para gerenciamento de cotas",
        "privacy.s1.li7": "Configuracoes de fuso horario: para exibicao personalizada de hora",
        "privacy.s1.li8": "Registros de consultas NTP: para avaliacao de confianca",
        "privacy.s1.h4": "1.3 Dados que NAO coletamos",
        "privacy.s2.p2": "NAO usaremos seus dados para: publicidade direcionada, criacao de perfis ou venda a terceiros.",
        "privacy.s5.li1": "Direito de acesso: solicitar a visualizacao de seus dados pessoais",
        "privacy.s5.li2": "Direito de retificacao: solicitar a correcao de dados imprecisos",
        "privacy.s5.li3": "Direito a portabilidade: solicitar seus dados em formato estruturado",
        "privacy.s5.li4": "Direito ao apagamento: solicitar a exclusao de seus dados pessoais",
        "privacy.s5.p2": "Para exercer qualquer direito, envie um e-mail para privacy@globetimezone.com. Responderemos em 30 dias.",
        "privacy.s6.p1": "Usamos apenas cookies essenciais para garantir a funcionalidade basica do site. NAO usamos cookies de rastreamento, publicitarios ou analiticos.",
        "privacy.s8.p3": "E-mail: privacy@globetimezone.com",
        "privacy.footer.terms": "Termos de servico",
        "privacy.footer.privacy": "Politica de privacidade",
        "privacy.footer.trust": "Garantia de confianca",
    },
    "ar": {
        "privacy.updated": "آخر تحديث: 2 يونيو 2026",
        "privacy.s1.h2": "1.1 جميع المستخدمين (مجاني + أعضاء PRO)",
        "privacy.s1.li1": "عنوان IP (مخفى الهوية، يحتفظ فقط بالبايتين الأولين لتحديد الموقع الجغرافي)",
        "privacy.s1.li3": "سجلات زيارة الصفحات (الصفحات التي تمت زيارتها، وقت الإقامة)",
        "privacy.s1.li4": "ملفات تعريف الارتباط الأساسية: لضمان وظيفة الموقع الأساسية",
        "privacy.s1.h3": "1.2 أعضاء PRO (جمع إضافي)",
        "privacy.s1.li5": "عنوان البريد الإلكتروني: للتحقق من الهوية وإشعارات الخدمة",
        "privacy.s1.li6": "طوابع وقت استدعاءات API: لإدارة الحصص وتحسين الخدمة",
        "privacy.s1.li7": "إعدادات المنطقة الزمنية: لعرض الوقت المخصص",
        "privacy.s1.li8": "سجلات استعلام حالة معايرة NTP: لتقييم الثقة والتحسين",
        "privacy.s1.h4": "1.3 البيانات التي لا نجمعها",
        "privacy.s2.p2": "لن نستخدم بياناتك من أجل: الإعلانات المستهدفة أو تنميط المستخدمين أو البيع لأطراف ثالثة.",
        "privacy.s5.li1": "حق الوصول: طلب الاطلاع على بياناتك الشخصية",
        "privacy.s5.li2": "حق التصحيح: طلب تصحيح البيانات غير الدقيقة",
        "privacy.s5.li3": "حق إمكانية النقل: طلب بياناتك بتنسيق منظم",
        "privacy.s5.li4": "حق الحذف: طلب حذف بياناتك الشخصية",
        "privacy.s5.p2": "لممارسة أي من الحقوق، يرجى مراسلتنا على privacy@globetimezone.com. سنرد خلال 30 يوما.",
        "privacy.s6.p1": "نستخدم فقط ملفات تعريف الارتباط الأساسية. لا نستخدم أي ملفات تعريف ارتباط للتتبع أو الإعلانات أو التحليلات.",
        "privacy.s8.p3": "البريد الإلكتروني: privacy@globetimezone.com",
        "privacy.footer.terms": "شروط الخدمة",
        "privacy.footer.privacy": "سياسة الخصوصية",
        "privacy.footer.trust": "ضمان الثقة",
    }
}

for lang in ['en', 'zh', 'de', 'fr', 'es', 'ja', 'ko', 'pt', 'ar']:
    with open(f'locales/{lang}.json', encoding='utf-8') as f:
        data = json.load(f)
    
    if lang == 'zh':
        for k, v in new_keys_zh.items():
            data[k] = v
    elif lang in translations:
        for k, v in translations[lang].items():
            data[k] = v
    
    with open(f'locales/{lang}.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2, sort_keys=True)
    
    print(f'{lang}: keys updated OK')

print('Done!')
