name = "globetimezone-widget"
main = "workers/widget/index.ts"
compatibility_date = "2026-05-30"
compatibility_flags = ["nodejs_compat"]
account_id = "b73e041dfa2e834c1cd23d11f1971cd5"

routes = [
  { pattern = "globetimezone.com/widget/*", zone_id = "4b8640caf424bf01cae67e92862961ef" },
  { pattern = "www.globetimezone.com/widget/*", zone_id = "4b8640caf424bf01cae67e92862961ef" }
]
