name = "tz-watcher"
main = "./workers/tz-watcher/index.ts"
compatibility_date = "2026-05-30"
compatibility_flags = ["nodejs_compat"]
account_id = "b73e041dfa2e834c1cd23d11f1971cd5"

[triggers]
crons = ["0 3 * * *"]

[[kv_namespaces]]
binding = "TZ_DATA"
id = "71c0cb3a54094834ab733f4537162fa0"
