#!/usr/bin/env python3
"""Generate 7 language JSON files for GlobeTimeZone i18n."""

import json
import os

LOCALES_DIR = os.path.join(os.path.dirname(__file__), "locales")

# Base keys order (from en.json)
KEYS_ORDER = [
    "meta.title", "meta.description",
    "nav.skipToContent", "nav.ariaLabel", "nav.timezones", "nav.meeting",
    "nav.crossborder", "nav.guides", "nav.upgrade", "nav.langButton", "nav.langButtonAriaLabel",
    "hero.badge", "hero.title", "hero.subtitle",
    "hero.search.placeholder", "hero.search.button", "hero.city.placeholder", "hero.city.button",
    "footer.about", "footer.privacy", "footer.terms", "footer.contact", "footer.copyright",
    "about.meta.title", "about.meta.desc", "about.h1",
    "apiguide.meta.title", "apiguide.meta.desc", "apiguide.h1",
    "api.meta.title", "api.meta.desc", "api.h1",
    "articles.meta.title", "articles.meta.desc", "articles.h1",
    "asttopst.meta.title", "asttopst.meta.desc", "asttopst.h1",
    "cettoest.meta.title", "cettoest.meta.desc", "cettoest.h1",
    "contact.meta.title", "contact.meta.desc", "contact.h1",
    "countdown.meta.title", "countdown.meta.desc", "countdown.h1",
    "disclaimer.meta.title", "disclaimer.h1",
    "distributedteamtimeculture.meta.title", "distributedteamtimeculture.meta.desc", "distributedteamtimeculture.h1",
    "dst2025schedule.meta.title", "dst2025schedule.meta.desc", "dst2025schedule.h1",
    "embedwidget.meta.title", "embedwidget.meta.desc", "embedwidget.h1",
    "esttocstconverter.meta.title", "esttocstconverter.meta.desc", "esttocstconverter.h1",
    "esttopstconverter.meta.title", "esttopstconverter.meta.desc", "esttopstconverter.h1",
    "europeaustraliatimedifference.meta.title", "europeaustraliatimedifference.meta.desc", "europeaustraliatimedifference.h1",
    "gmttocstconverter.meta.title", "gmttocstconverter.meta.desc", "gmttocstconverter.h1",
    "hawaiitoest.meta.title", "hawaiitoest.meta.desc", "hawaiitoest.h1",
    "holidays.meta.title", "holidays.meta.desc", "holidays.h1",
    "isttoestconverter.meta.title", "isttoestconverter.meta.desc", "isttoestconverter.h1",
    "jsttocstconverter.meta.title", "jsttocstconverter.meta.desc", "jsttocstconverter.h1",
    "meetingscheduler.meta.title", "meetingscheduler.meta.desc", "meetingscheduler.h1",
    "privacypolicy.meta.title", "privacypolicy.h1",
    "privacy.meta.title", "privacy.meta.desc", "privacy.h1",
    "pro.meta.title", "pro.meta.desc", "pro.h1",
    "psttocstconverter.meta.title", "psttocstconverter.meta.desc", "psttocstconverter.h1",
    "psttoest.meta.title", "psttoest.meta.desc", "psttoest.h1",
    "remoteteamtimezoneguide.meta.title", "remoteteamtimezoneguide.meta.desc", "remoteteamtimezoneguide.h1",
    "remoteteamtimezonetools.meta.title", "remoteteamtimezonetools.meta.desc", "remoteteamtimezonetools.h1",
    "remoteworktimezone.meta.title", "remoteworktimezone.meta.desc", "remoteworktimezone.h1",
    "subscribe.meta.title", "subscribe.meta.desc", "subscribe.h1",
    "teamoverlap.meta.title", "teamoverlap.meta.desc", "teamoverlap.h1",
    "terms.meta.title", "terms.meta.desc", "terms.h1",
    "timedifference.chicagototokyo.meta.title", "timedifference.chicagototokyo.meta.desc", "timedifference.chicagototokyo.h1",
    "timedifference.dubaitolosangeles.meta.title", "timedifference.dubaitolosangeles.meta.desc", "timedifference.dubaitolosangeles.h1",
    "timedifference.frankfurttonewyork.meta.title", "timedifference.frankfurttonewyork.meta.desc", "timedifference.frankfurttonewyork.h1",
    "timedifference.hongkongtolosangeles.meta.title", "timedifference.hongkongtolosangeles.meta.desc", "timedifference.hongkongtolosangeles.h1",
    "timedifference.latobeijing.meta.title", "timedifference.latobeijing.meta.desc", "timedifference.latobeijing.h1",
    "timedifference.miamitolondon.meta.title", "timedifference.miamitolondon.meta.desc", "timedifference.miamitolondon.h1",
    "timedifference.mumbaitodubai.meta.title", "timedifference.mumbaitodubai.meta.desc", "timedifference.mumbaitodubai.h1",
    "timedifference.newyorktolondon.meta.title", "timedifference.newyorktolondon.meta.desc", "timedifference.newyorktolondon.h1",
    "timedifference.nuevayorkalondres.meta.title", "timedifference.nuevayorkalondres.meta.desc", "timedifference.nuevayorkalondres.h1",
    "timedifference.paristonewyork.meta.title", "timedifference.paristonewyork.meta.desc", "timedifference.paristonewyork.h1",
    "timedifference.seoultolondon.meta.title", "timedifference.seoultolondon.meta.desc", "timedifference.seoultolondon.h1",
    "timedifference.singaporetolondon.meta.title", "timedifference.singaporetolondon.meta.desc", "timedifference.singaporetolondon.h1",
    "timedifference.sydneytolondon.meta.title", "timedifference.sydneytolondon.meta.desc", "timedifference.sydneytolondon.h1",
    "timedifference.sydneytonewyork.meta.title", "timedifference.sydneytonewyork.meta.desc", "timedifference.sydneytonewyork.h1",
    "timedifference.tokyotonewyork.meta.title", "timedifference.tokyotonewyork.meta.desc", "timedifference.tokyotonewyork.h1",
    "timedifference.torontotoshanghai.meta.title", "timedifference.torontotoshanghai.meta.desc", "timedifference.torontotoshanghai.h1",
    "timedifference.洛杉矶到北京.meta.title", "timedifference.洛杉矶到北京.meta.desc", "timedifference.洛杉矶到北京.h1",
    "timein.beijing.meta.title", "timein.beijing.meta.desc", "timein.beijing.h1",
    "timein.chicago.meta.title", "timein.chicago.meta.desc", "timein.chicago.h1",
    "timein.dubai.meta.title", "timein.dubai.meta.desc", "timein.dubai.h1",
    "timein.london.meta.title", "timein.london.meta.desc", "timein.london.h1",
    "timein.losangeles.meta.title", "timein.losangeles.meta.desc", "timein.losangeles.h1",
    "timein.newyork.meta.title", "timein.newyork.meta.desc", "timein.newyork.h1",
    "timein.paris.meta.title", "timein.paris.meta.desc", "timein.paris.h1",
    "timein.seoul.meta.title", "timein.seoul.meta.desc", "timein.seoul.h1",
    "timein.singapore.meta.title", "timein.singapore.meta.desc", "timein.singapore.h1",
    "timein.sydney.meta.title", "timein.sydney.meta.desc", "timein.sydney.h1",
    "timein.tokyo.meta.title", "timein.tokyo.meta.desc", "timein.tokyo.h1",
    "timein.toronto.meta.title", "timein.toronto.meta.desc", "timein.toronto.h1",
    "timeunits.meta.title", "timeunits.meta.desc", "timeunits.h1",
    "timestampevidence.meta.title", "timestampevidence.meta.desc", "timestampevidence.h1",
    "timezoneguide.meta.title", "timezoneguide.meta.desc", "timezoneguide.h1",
    "timezonehistory.meta.title", "timezonehistory.meta.desc", "timezonehistory.h1",
    "uschinatimedifference.meta.title", "uschinatimedifference.meta.desc", "uschinatimedifference.h1",
    "utc8toutc5.meta.title", "utc8toutc5.meta.desc", "utc8toutc5.h1",
    "utctocstconverter.meta.title", "utctocstconverter.meta.desc", "utctocstconverter.h1",
    "whydaylightsavingtime.meta.title", "whydaylightsavingtime.meta.desc", "whydaylightsavingtime.h1",
    "worldclock.meta.title", "worldclock.meta.desc", "worldclock.h1",
    "worldmap.meta.title", "worldmap.meta.desc", "worldmap.h1",
]

# =============================================================================
# DEUTSCH (de)
# =============================================================================
de = {
    "meta.title": "GlobeTimeZone — Globales Zeitentscheidungstool",
    "meta.description": "Sofort wissen, ob man sich melden oder eine Besprechung planen sollte. Globale Rhythmen in Echtzeit fühlen.",
    "nav.skipToContent": "Zum Hauptinhalt springen",
    "nav.ariaLabel": "Hauptnavigation",
    "nav.timezones": "Zeitzonen",
    "nav.meeting": "Besprechungsplaner",
    "nav.crossborder": "Grenzüberschreitend",
    "nav.guides": "Leitfäden",
    "nav.upgrade": "PRO Upgrade",
    "nav.langButton": "🌐 Deutsch ▾",
    "nav.langButtonAriaLabel": "Sprache wechseln",
    "hero.badge": "🌏 Weltweit gerade jetzt",
    "hero.title": "Weiß, wie spät es ist,<br>überall. Sofort.",
    "hero.subtitle": "San Francisco schläft. London fängt an zu arbeiten. Tokyo läutet den Abend ein.<br>Kein Kopfrechnen, keine Umrechnung — den globalen Rhythmus auf einen Blick fühlen.",
    "hero.search.placeholder": "Beliebige Stadt suchen… Tokyo, London, New York, Paris…",
    "hero.search.button": "🔍 Suchen",
    "hero.city.placeholder": "Stadt zum Dashboard hinzufügen…",
    "hero.city.button": "+ Hinzufügen",
    "footer.about": "Über uns",
    "footer.privacy": "Datenschutz",
    "footer.terms": "Nutzungsbedingungen",
    "footer.contact": "Kontakt",
    "footer.copyright": "© 2026 GlobeTimeZone · Alle Zeitdaten via NTP kalibriert · Zeitzonendaten via IANA",
    "about.meta.title": "Über GlobeTimeZone – Unsere Geschichte & Mission",
    "about.meta.desc": "Erfahren Sie mehr über GlobeTimeZone.",
    "about.h1": "Unsere Geschichte",
    "apiguide.meta.title": "Zeitzonen-API-Leitfaden für Entwickler: Zeiten programmgesteuert umrechnen | GlobeTimeZone",
    "apiguide.meta.desc": "Vollständiger Entwicklerleitfaden für Zeitzonen-APIs. Zeiten umrechnen, Sommerzeit erkennen und Zeitzonen in Ihren Apps verwalten. Öffentliche APIs vergleichen, Codebeispiele für JavaScript, Python und mehr.",
    "apiguide.h1": "Zeitzonen-API-Leitfaden für Entwickler: Zeiten programmgesteuert umrechnen",
    "api.meta.title": "GlobeTimeZone API - Kostenlose Zeitzonendaten & Umrechnungs-API | Dokumentation",
    "api.meta.desc": "Kostenlose API für Zeitzonenumrechnung, aktuelle Zeit und Zeitzonendaten. RESTful-Endpunkte mit JSON-Antworten. Kein API-Schlüssel für die Basisversion erforderlich. Weltzeit in Ihre Apps integrieren.",
    "api.h1": "⚡ GlobeTimeZone API",
    "articles.meta.title": "Zeitzonen-Artikel & Leitfäden – GlobeTimeZone.com",
    "articles.meta.desc": "Erfahren Sie mehr über Zeitzonen, Sommerzeit, UTC und wie Sie Zeitunterschiede für Geschäft und Reise verwalten.",
    "articles.h1": "📖 Zeitzonen-Artikel & Leitfäden",
    "asttopst.meta.title": "AST zu PST Konverter (2026): Vollständige Zeittabelle & Karibik-US-West Besprechungszeiten",
    "asttopst.meta.desc": "Atlantische Standardzeit schnell in Pazifikzeit umrechnen. 24-Stunden-Tabelle, Sommerzeit-Daten 2026, beste Anrufzeiten & Praxistipps.",
    "asttopst.h1": "🏝️ AST zu PST Konverter",
    "cettoest.meta.title": "CET zu EST Konverter (2026): Vollständige Zeittabelle & Europa-US Besprechungszeiten",
    "cettoest.meta.desc": "Mitteleuropäische Zeit schnell in US-Ostküstenzeit umrechnen. 24-Stunden-Tabelle, Sommerzeit 2026, beste Anrufzeiten & typische Planungsfehler.",
    "cettoest.h1": "🏰 CET zu EST Konverter",
    "contact.meta.title": "Kontakt – GlobeTimeZone",
    "contact.meta.desc": "Kontaktieren Sie GlobeTimeZone. Fragen, Feedback, Partnerschaften oder geschäftliche Anfragen.",
    "contact.h1": "📬 Kontakt",
    "countdown.meta.title": "Event-Countdown-Timer - Countdown in mehreren Zeitzonen | GlobeTimeZone",
    "countdown.meta.desc": "Erstellen Sie Countdowns für Events und sehen Sie sie gleichzeitig in mehreren Zeitzonen. Perfekt für globale Teamfeiern, Produktlaunches und internationale Deadlines.",
    "countdown.h1": "⏱️ Event-Countdown-Timer",
    "disclaimer.meta.title": "Haftungsausschluss – GlobeTimeZone.com",
    "disclaimer.h1": "Haftungsausschluss",
    "distributedteamtimeculture.meta.title": "Wie verteilte Teams eine „Zeitrespekt\"-Kultur aufbauen können | GlobeTimeZone",
    "distributedteamtimeculture.meta.desc": "Praktische Strategien für den Aufbau einer zeitrespektierenden Kultur in verteilten Teams. Ankerzeiten festlegen, asynchrone Kommunikation priorisieren und Zeitzonen-Tools zur Burnout-Prävention nutzen.",
    "distributedteamtimeculture.h1": "Wie verteilte Teams eine „Zeitrespekt\"-Kultur aufbauen können",
    "dst2025schedule.meta.title": "2025 Globale Sommerzeit-Zeitplan & Daten | GlobeTimeZone",
    "dst2025schedule.meta.desc": "Vollständiger Sommerzeit-Plan 2025: Start- und Enddaten für USA, UK, EU, Australien, Neuseeland und mehr. Keine Uhrenumstellung mehr verpassen.",
    "dst2025schedule.h1": "2025 Globale Sommerzeit-Zeitplan: Vollständige Start- & Enddaten",
    "embedwidget.meta.title": "Kostenloses einbettbares Weltuhren-Widget | GlobeTimeZone",
    "embedwidget.meta.desc": "Fügen Sie ein kostenloses Weltuhren-Widget zu Ihrer Website hinzu. Anpassbare Städte, Hell-/Dunkel-Theme, kompakt oder voll. Embed-Code in Sekunden kopieren.",
    "embedwidget.h1": "🆓 Kostenloses Weltuhren-Widget",
    "esttocstconverter.meta.title": "EST zu CST Konverter - Ost- nach Mittelzeit | GlobeTimeZone",
    "esttocstconverter.meta.desc": "EST (Eastern Standard Time) sofort in CST (Central Standard Time) umrechnen. Kostenloser Konverter mit 24-Stunden-Tabelle und Besprechungstipps.",
    "esttocstconverter.h1": "🕐 EST zu CST Konverter",
    "esttopstconverter.meta.title": "EST zu PST Konverter - Ost- nach Pazifikzeit | GlobeTimeZone",
    "esttopstconverter.meta.desc": "EST (Eastern Standard Time) sofort in PST (Pacific Standard Time) umrechnen. Kostenloser Konverter mit 24-Stunden-Tabelle. 3 Stunden Zeitunterschied.",
    "esttopstconverter.h1": "🕐 EST zu PST Konverter",
    "europeaustraliatimedifference.meta.title": "Europa vs. Australien Zeitunterschied (2026): Vollständige 24-Stunden-Tabelle & beste Besprechungszeiten",
    "europeaustraliatimedifference.meta.desc": "Europa- und Australien-Zeitzonen sofort vergleichen. Vollständige Umrechnungstabelle, Sommerzeit-Verschiebungen, beste Anrufzeiten & typische Planungsfehler.",
    "europeaustraliatimedifference.h1": "🦘 Europa nach Australien Zeitkonverter",
    "gmttocstconverter.meta.title": "GMT zu CST Konverter - Greenwich nach China Standard Time | GlobeTimeZone",
    "gmttocstconverter.meta.desc": "GMT (Greenwich Mean Time) sofort in CST (China Standard Time) umrechnen. Kostenloser Konverter mit 24-Stunden-Tabelle und Arbeitszeitanzeige.",
    "gmttocstconverter.h1": "🕐 GMT zu CST Konverter",
    "hawaiitoest.meta.title": "Hawaii-Zeit zu EST Konverter (2026): Vollständige Zeittabelle & beste US-Besprechungszeiten",
    "hawaiitoest.meta.desc": "Hawaii-Aleuten-Zeit schnell in US-Ostküstenzeit umrechnen. 24-Stunden-Tabelle, Sommerzeit 2026, beste Anrufzeiten & typische Planungsfehler.",
    "hawaiitoest.h1": "🌺 Hawaii zu EST Konverter",
    "holidays.meta.title": "Weltweite Feiertage 2026 - Gesetzliche Feiertage in 200+ Ländern | GlobeTimeZone",
    "holidays.meta.desc": "Gesetzliche Feiertage und Gedenktage in 200+ Ländern. Perfekt für internationale Geschäftsplanung, Reisen und kulturelles Verständnis.",
    "holidays.h1": "🎉 Weltweite Feiertage 2026",
    "isttoestconverter.meta.title": "IST zu EST Konverter | Indien nach Ostküstenzeit | GlobeTimeZone",
    "isttoestconverter.meta.desc": "IST (India Standard Time, UTC+5:30) in EST (Eastern Standard Time, UTC-5) umrechnen. Interaktiver Konverter, 24-Stunden-Tabelle und beste Besprechungszeiten zwischen Indien und der US-Ostküste.",
    "isttoestconverter.h1": "IST zu EST Zeitkonverter",
    "jsttocstconverter.meta.title": "JST zu CST Konverter - Japan nach China Standard Time | GlobeTimeZone",
    "jsttocstconverter.meta.desc": "JST (Japan Standard Time) sofort in CST (China Standard Time) umrechnen. Kostenloser Konverter. Japan und China teilen denselben UTC+8-Offset.",
    "jsttocstconverter.h1": "🕐 JST zu CST Konverter",
    "meetingscheduler.meta.title": "Besprechungsplaner - Beste Besprechungszeiten über Zeitzonen finden | GlobeTimeZone",
    "meetingscheduler.meta.desc": "Kostenloser intelligenter Besprechungsplaner. Finden Sie die besten Besprechungszeiten über mehrere Zeitzonen. Unterstützt Teamplanung mit Arbeitszeitanzeige.",
    "meetingscheduler.h1": "📅 Besprechungsplaner",
    "privacypolicy.meta.title": "Datenschutz - GlobeTimeZone",
    "privacypolicy.h1": "🔒 Datenschutz",
    "privacy.meta.title": "Datenschutz – GlobeTimeZone",
    "privacy.meta.desc": "GlobeTimeZone Datenschutzrichtlinie. Wir verkaufen Ihre Daten nicht.",
    "privacy.h1": "Datenschutz",
    "pro.meta.title": "GlobeTimeZone Pro - Premium-Funktionen für Power-User",
    "pro.meta.desc": "Upgrade auf GlobeTimeZone Pro für unbegrenzte Uhren, werbefreies Erlebnis, API-Zugang und Prioritäts-Support.",
    "pro.h1": "🚀 GlobeTimeZone Pro",
    "psttocstconverter.meta.title": "PST zu CST Konverter | Pazifik nach China Standard Time | GlobeTimeZone",
    "psttocstconverter.meta.desc": "PST (Pacific Standard Time, UTC-8) in CST (China Standard Time, UTC+8) umrechnen. 24-Stunden-Tabelle, Schnellkonverter und beste Zeiten für Anrufe zwischen Kalifornien und China.",
    "psttocstconverter.h1": "PST zu CST (China) Zeitkonverter",
    "psttoest.meta.title": "PST zu EST Konverter (2026): Vollständige Zeittabelle & beste US-Querbesprechungszeiten",
    "psttoest.meta.desc": "Pazifikzeit schnell in Ostzeit umrechnen. 24-Stunden-Tabelle, Sommerzeit-Daten 2026, beste Zeitfenster & typische Zeitzonenfehler.",
    "psttoest.h1": "🗼 PST zu EST Konverter",
    "remoteteamtimezoneguide.meta.title": "Leitfaden für Zeitzonenmanagement in Remote-Teams | GlobeTimeZone",
    "remoteteamtimezoneguide.meta.desc": "Vollständiger Leitfaden für das Management von Remote-Teams über Zeitzonen. Besprechungen planen, Produktivität erhalten und Kultur in verteilten Teams aufbauen.",
    "remoteteamtimezoneguide.h1": "🤝 Leitfaden für Zeitzonenmanagement in Remote-Teams",
    "remoteteamtimezonetools.meta.title": "Beste Zeitzonen-Tools für Remote-Teams im Vergleich: Leitfaden 2025 | GlobeTimeZone",
    "remoteteamtimezonetools.meta.desc": "Vergleichen Sie die besten Zeitzonen-Tools für Remote-Teams: Slack, Google Calendar, World Time Buddy, Clockwise und mehr. Wählen Sie das richtige Tool für Ihr verteiltes Team.",
    "remoteteamtimezonetools.h1": "Beste Zeitzonen-Tools für Remote-Teams im Vergleich: Leitfaden 2025",
    "remoteworktimezone.meta.title": "Remote-Arbeit & globales Team Zeitzonen-Leitfaden | GlobeTimeZone",
    "remoteworktimezone.meta.desc": "Zeitzonen in Remote- oder verteilten Teams managen. Best Practices für Besprechungsplanung, Kernarbeitszeiten und Vermeidung von Zeitzonen-Erschöpfung in globalen Teams.",
    "remoteworktimezone.h1": "Das vollständige Remote-Team Zeitzonen-Handbuch",
    "subscribe.meta.title": "GlobeTimeZone abonnieren - Wöchentliche Zeitzonen-Tipps & Updates",
    "subscribe.meta.desc": "Abonnieren Sie GlobeTimeZone für Zeitzonen-Tipps und Updates.",
    "subscribe.h1": "📬 Mit GlobeTimeZone synchron bleiben",
    "teamoverlap.meta.title": "Team-Zeitüberlappungsrechner - Gemeinsame Arbeitszeiten finden | GlobeTimeZone",
    "teamoverlap.meta.desc": "Überlappende Arbeitszeiten für Ihr Remote-Team über Zeitzonen finden. Visuelles Team-Panel, um zu sehen, wann alle verfügbar sind. Perfekt für verteilte Teams.",
    "teamoverlap.h1": "👥 Team-Zeitüberlappungsrechner",
    "terms.meta.title": "Nutzungsbedingungen – GlobeTimeZone",
    "terms.meta.desc": "GlobeTimeZone Nutzungsbedingungen. Unser Tool ist für persönliche und kommerzielle Nutzung kostenlos.",
    "terms.h1": "Nutzungsbedingungen",
    "timedifference.chicagototokyo.meta.title": "Zeitunterschied zwischen Chicago und Tokyo (2026)",
    "timedifference.chicagototokyo.meta.desc": "Chicago nach Tokyo: Das Herzland trifft Japan über 14-15 Stunden. Vollständiger Zeitvergleich, beste Anrufzeiten & Praxiserfahrungen.",
    "timedifference.chicagototokyo.h1": "Zeitunterschied zwischen Chicago und Tokyo (2026): Amerikas Herzland trifft Japan",
    "timedifference.dubaitolosangeles.meta.title": "Zeitunterschied zwischen Dubai und Los Angeles (2026): Vollständiger Leitfaden",
    "timedifference.dubaitolosangeles.meta.desc": "Dubai nach LA umfasst 12-13 Stunden ohne Arbeitszeitüberlappung. Vollständiger Planungsleitfaden mit asymmetrischer Flexibilitätsstrategie.",
    "timedifference.dubaitolosangeles.h1": "Zeitunterschied zwischen Dubai und Los Angeles (2026): Vom Golf zum Pazifik",
    "timedifference.frankfurttonewyork.meta.title": "Zeitunterschied zwischen Frankfurt und New York (2026): Finanzleitfaden",
    "timedifference.frankfurttonewyork.meta.desc": "Frankfurt und New York treiben die weltweiten Finanzmärkte. Vollständiger Zeitvergleich, Handelsfenster & Praxiserfahrungen.",
    "timedifference.frankfurttonewyork.h1": "Zeitunterschied zwischen Frankfurt und New York (2026): Europäische Finanzen treffen amerikanische Märkte",
    "timedifference.hongkongtolosangeles.meta.title": "Zeitunterschied zwischen Hongkong und Los Angeles (2026): Vollständiger Leitfaden",
    "timedifference.hongkongtolosangeles.meta.desc": "Hongkong nach LA überquert den Pazifik mit 15-16 Stunden. Vollständiger Planungsleitfaden, beste Anrufzeiten & Praxiserfahrungen.",
    "timedifference.hongkongtolosangeles.h1": "Zeitunterschied zwischen Hongkong und Los Angeles (2026): Asiens Finanzherz trifft Hollywood",
    "timedifference.latobeijing.meta.title": "Zeitunterschied zwischen Los Angeles und Peking (2026): Transpazifische Praxis",
    "timedifference.latobeijing.meta.desc": "Anrufe zwischen LA und Peking planen? Die 15-16 Stunden Lücke bedeutet, dass immer eine Partei außerhalb der Arbeitszeit arbeitet. Vollständige Planungsstrategien.",
    "timedifference.latobeijing.h1": "Zeitunterschied zwischen Los Angeles und Peking (2026): Transpazifische Praxis",
    "timedifference.miamitolondon.meta.title": "Zeitunterschied zwischen Miami und London (2026)",
    "timedifference.miamitolondon.meta.desc": "Miami nach London: Sonne trifft Nebel über 5-7 Stunden. Vollständiger Zeitvergleich, beste Anrufzeiten & Praxiserfahrungen.",
    "timedifference.miamitolondon.h1": "Zeitunterschied zwischen Miami und London (2026): Sonne trifft Nebel",
    "timedifference.mumbaitodubai.meta.title": "Zeitunterschied zwischen Mumbai und Dubai (2026)",
    "timedifference.mumbaitodubai.meta.desc": "Mumbai nach Dubai: Südasien trifft den Golf über nur 1,5 Stunden. Vollständiger Zeitvergleich und beste Anrufzeiten.",
    "timedifference.mumbaitodubai.h1": "Zeitunterschied zwischen Mumbai und Dubai (2026): Nahe Nachbarn",
    "timedifference.newyorktolondon.meta.title": "Zeitunterschied zwischen New York und London (2026): Vollständiger Leitfaden für Finanzen, Tech & Business",
    "timedifference.newyorktolondon.meta.desc": "New York-London Zeitunterschied erklärt: 4-5 Stunden je nach Sommerzeit. Finanz-/Handelsfenster, Tech-Meeting-Tipps, Sommerzeit-Daten 2026 und kostenloser Konverter. Expertenleitfaden.",
    "timedifference.newyorktolondon.h1": "Zeitunterschied zwischen New York und London (2026): Der vollständige Business- & Finanzleitfaden",
    "timedifference.nuevayorkalondres.meta.title": "Zeitunterschied zwischen New York und London (2026): Konverter & beste Besprechungszeiten",
    "timedifference.nuevayorkalondres.meta.desc": "Sofortige Umrechnung zwischen New York und London mit unserem kostenlosen Tool. Sommerzeit 2026, beste Besprechungszeiten und häufige Planungsfehler.",
    "timedifference.nuevayorkalondres.h1": "Zeitunterschied zwischen New York und London (2026): Vollständiger Konverter & beste Besprechungszeiten",
    "timedifference.paristonewyork.meta.title": "Zeitunterschied zwischen Paris und New York (2026): Vollständiger Leitfaden",
    "timedifference.paristonewyork.meta.desc": "Paris nach New York ist eine der einfacheren transatlantischen Routen — bis die Sommerzeit Sie überrascht. Vollständiger Zeitvergleich & Fallstricke.",
    "timedifference.paristonewyork.h1": "Zeitunterschied zwischen Paris und New York (2026): Die fast einfache Route",
    "timedifference.seoultolondon.meta.title": "Zeitunterschied zwischen Seoul und London (2026)",
    "timedifference.seoultolondon.meta.desc": "Seoul nach London: K-Kultur trifft britische Tradition über 8-9 Stunden. Vollständiger Zeitvergleich, beste Anrufzeiten & Praxiserfahrungen.",
    "timedifference.seoultolondon.h1": "Zeitunterschied zwischen Seoul und London (2026): K-Kultur-Hauptstadt trifft Großbritannien",
    "timedifference.singaporetolondon.meta.title": "Zeitunterschied zwischen Singapur und London (2026)",
    "timedifference.singaporetolondon.meta.desc": "Singapur nach London umfasst 7-8 Stunden über Kontinente. Praxiserfahrungen für Anrufe zwischen der Löwenstadt und der City of London, inklusive Finanz- und Handelstipps.",
    "timedifference.singaporetolondon.h1": "Zeitunterschied zwischen Singapur und London (2026): Der vollständige Business-Leitfaden",
    "timedifference.sydneytolondon.meta.title": "Zeitunterschied zwischen Sydney und London (2026): Vollständiger Leitfaden",
    "timedifference.sydneytolondon.meta.desc": "Sydney nach London umfasst fast 17.000 km mit komplexen Sommerzeit-Überlappungen. Jahrelange Erfahrung mit dieser Route, inklusive Planungsstrategien.",
    "timedifference.sydneytolondon.h1": "Zeitunterschied zwischen Sydney und London (2026): Gegenseitige Hemisphären navigieren",
    "timedifference.sydneytonewyork.meta.title": "Zeitunterschied zwischen Sydney und New York (2026)",
    "timedifference.sydneytonewyork.meta.desc": "Sydney nach New York: Gegenseitige Hemisphären, 14-19 Stunden Lücke. Vollständiger Zeitvergleich, beste Anrufzeiten & Praxiserfahrungen.",
    "timedifference.sydneytonewyork.h1": "Zeitunterschied zwischen Sydney und New York (2026): Gegenseitige Hemisphären",
    "timedifference.tokyotonewyork.meta.title": "Zeitunterschied zwischen Tokyo und New York (2026): Der ultimative Business- & Reiseleitfaden",
    "timedifference.tokyotonewyork.meta.desc": "Vollständiger Tokyo-New York Zeitzonenleitfaden: 13-14 Stunden Unterschied erklärt. Business-Meeting-Planer, Sommerzeit 2026, Branchentipps für Finanzen, Tech & Entertainment. Kostenloser Konverter inklusive.",
    "timedifference.tokyotonewyork.h1": "Zeitunterschied zwischen Tokyo und New York (2026): Der vollständige Business- & Reiseleitfaden",
    "timedifference.torontotoshanghai.meta.title": "Zeitunterschied zwischen Toronto und Shanghai (2026): Vollständiger Leitfaden",
    "timedifference.torontotoshanghai.meta.desc": "Toronto-Shanghai hat keine Arbeitszeitüberlappung — die 12-13 Stunden Lücke bedeutet, dass immer jemand außerhalb der Arbeitszeit online sein muss. Vollständige Planungsstrategien.",
    "timedifference.torontotoshanghai.h1": "Zeitunterschied zwischen Toronto und Shanghai (2026): Die Route ohne Überlappung managen",
    "timedifference.洛杉矶到北京.meta.title": "Zeitunterschied zwischen Los Angeles und Peking (2026): Vollständige Umrechnungstabelle & beste Anrufzeiten",
    "timedifference.洛杉矶到北京.meta.desc": "Genaue Zeitunterschiede zwischen LA und Peking, 24-Stunden-Umrechnungstabelle, Sommerzeit 2026 und beste Zeiten für transpazifische Business-Anrufe.",
    "timedifference.洛杉矶到北京.h1": "Zeitunterschied zwischen Los Angeles und Peking (2026): Vollständige Umrechnungstabelle & beste Anrufzeiten",
    "timein.beijing.meta.title": "Aktuelle Zeit in Peking | Zeitzone, Datum | GlobeTimeZone",
    "timein.beijing.meta.desc": "Aktuelle Zeit in Peking, China. Genaue Zeit, Datum, Zeitzonenversatz (CST, UTC+8). Keine Sommerzeit. Mit anderen Städten weltweit vergleichen.",
    "timein.beijing.h1": "Aktuelle Zeit in Peking",
    "timein.chicago.meta.title": "Aktuelle Zeit in Chicago | CST/CDT Zeitzone | GlobeTimeZone",
    "timein.chicago.meta.desc": "Aktuelle Zeit in Chicago, Illinois. Live-Uhr, CST/CDT Central Time (UTC-6/UTC-5), Sommerzeit-Status und Vergleich mit großen Weltstädten.",
    "timein.chicago.h1": "Aktuelle Zeit in Chicago",
    "timein.dubai.meta.title": "Aktuelle Zeit in Dubai | GST (UTC+4) Zeitzone | GlobeTimeZone",
    "timein.dubai.meta.desc": "Aktuelle Zeit in Dubai, VAE. Live-Uhr, GST Zeitzone (UTC+4), keine Sommerzeit. Dubai-Zeit mit Weltstädten vergleichen.",
    "timein.dubai.h1": "Aktuelle Zeit in Dubai",
    "timein.london.meta.title": "Aktuelle Zeit in London | Zeitzone, Datum | GlobeTimeZone",
    "timein.london.meta.desc": "Aktuelle Zeit in London, UK. Genaue Zeit, Datum, Zeitzonenversatz (GMT/BST), Sonnenauf- und -untergangszeiten. Mit anderen Städten weltweit vergleichen.",
    "timein.london.h1": "Aktuelle Zeit in London",
    "timein.losangeles.meta.title": "Aktuelle Zeit in Los Angeles | PST/PDT Zeitzone | GlobeTimeZone",
    "timein.losangeles.meta.desc": "Aktuelle Zeit in Los Angeles, Kalifornien. Live-Uhr, PST/PDT Pacific Time (UTC-8/UTC-7), Sommerzeit-Status und weltweiter Stadtvergleich.",
    "timein.losangeles.h1": "Aktuelle Zeit in Los Angeles",
    "timein.newyork.meta.title": "Aktuelle Zeit in New York | Zeitzone, Datum | GlobeTimeZone",
    "timein.newyork.meta.desc": "Aktuelle Zeit in New York, USA. Genaue Zeit, Datum, Zeitzonenversatz (EST/EDT). Mit anderen Städten weltweit vergleichen.",
    "timein.newyork.h1": "Aktuelle Zeit in New York",
    "timein.paris.meta.title": "Aktuelle Zeit in Paris | CET/CEST Zeitzone | GlobeTimeZone",
    "timein.paris.meta.desc": "Aktuelle Zeit in Paris, Frankreich. Live-Uhr, Datum, CET/CEST Zeitzonenversatz, Sommerzeit-Status. Paris-Zeit mit anderen Weltstädten vergleichen.",
    "timein.paris.h1": "Aktuelle Zeit in Paris",
    "timein.seoul.meta.title": "Aktuelle Zeit in Seoul | KST (UTC+9) Zeitzone | GlobeTimeZone",
    "timein.seoul.meta.desc": "Aktuelle Zeit in Seoul, Südkorea. Live-Uhr, KST Zeitzone (UTC+9), keine Sommerzeit und Vergleich mit Weltstädten inklusive Peking, Tokyo und New York.",
    "timein.seoul.h1": "Aktuelle Zeit in Seoul",
    "timein.singapore.meta.title": "Aktuelle Zeit in Singapur | SGT (UTC+8) Zeitzone | GlobeTimeZone",
    "timein.singapore.meta.desc": "Aktuelle Zeit in Singapur. Live-Uhr, SGT Zeitzone (UTC+8), keine Sommerzeit. Singapur-Zeit mit London, New York, Peking und mehr vergleichen.",
    "timein.singapore.h1": "Aktuelle Zeit in Singapur",
    "timein.sydney.meta.title": "Aktuelle Zeit in Sydney | AEDT/AEST Zeitzone | GlobeTimeZone",
    "timein.sydney.meta.desc": "Aktuelle Zeit in Sydney, Australien. Live-Uhr, AEDT/AEST Zeitzone (UTC+11/UTC+10), Sommerzeit-Status und Weltstadtvergleich.",
    "timein.sydney.h1": "Aktuelle Zeit in Sydney",
    "timein.tokyo.meta.title": "Aktuelle Zeit in Tokyo | Zeitzone, Datum | GlobeTimeZone",
    "timein.tokyo.meta.desc": "Aktuelle Zeit in Tokyo, Japan. Genaue Zeit, Datum, Zeitzonenversatz (JST, UTC+9). Keine Sommerzeit. Mit anderen Städten weltweit vergleichen.",
    "timein.tokyo.h1": "Aktuelle Zeit in Tokyo",
    "timein.toronto.meta.title": "Aktuelle Zeit in Toronto | EST/EDT Zeitzone | GlobeTimeZone",
    "timein.toronto.meta.desc": "Aktuelle Zeit in Toronto, Kanada. Live-Uhr, EST/EDT Eastern Time (UTC-5/UTC-4), Sommerzeit-Status und Weltstadtvergleich.",
    "timein.toronto.h1": "Aktuelle Zeit in Toronto",
    "timeunits.meta.title": "Zeiteinheiten-Konverter - Stunden, Minuten, Sekunden, Dezimalzeit | GlobeTimeZone",
    "timeunits.meta.desc": "Kostenloser Zeiteinheiten-Konverter. Umrechnung zwischen Stunden, Minuten, Sekunden, Dezimalstunden und mehr. Perfekt für Gehaltsabrechnung, Projektmanagement und Zeiterfassung.",
    "timeunits.h1": "🔄 Zeiteinheiten-Konverter",
    "timestampevidence.meta.title": "GlobeTimeZone - Digitaler Zeitstempel-Nachweis",
    "timestampevidence.meta.desc": "Hochverlässlicher digitaler Zeitstempel-Nachweis - Konform mit dem Signaturgesetz",
    "timestampevidence.h1": "GlobeTimeZone Hochverlässlicher digitaler Zeitstempel-Nachweis",
    "timezoneguide.meta.title": "Vollständiger Leitfaden zu Weltzeitzonen | GlobeTimeZone",
    "timezoneguide.meta.desc": "Alles, was Sie über Weltzeitzonen wissen müssen: UTC-Versätze, Funktionsweise, die IANA-Datenbank, UTC vs. GMT und Tipps für zeitzonenübergreifende Planung.",
    "timezoneguide.h1": "Vollständiger Leitfaden zu Weltzeitzonen",
    "timezonehistory.meta.title": "Faszinierende Zeitzonengeschichte: Die Datumsgrenze, Samoas verlorener Tag und mehr | GlobeTimeZone",
    "timezonehistory.meta.desc": "Entdecken Sie die faszinierendsten Geschichten der Zeitzonengeschichte: Wie die internationale Datumsgrenze entstand, warum Samoa einen Tag übersprang, das Chaos der Eisenbahnzeit und die Politik von UTC.",
    "timezonehistory.h1": "Faszinierende Zeitzonengeschichte: Die Datumsgrenze, verlorene Tage und Eisenbahn-Chaos",
    "uschinatimedifference.meta.title": "USA vs. China Zeitunterschied – GlobeTimeZone.com",
    "uschinatimedifference.meta.desc": "Wie groß ist der Zeitunterschied zwischen den USA und China? Vollständiger Leitfaden zu US-China-Zeitzonen, Sommerzeit und besten Anrufzeiten.",
    "uschinatimedifference.h1": "USA vs. China Zeitunterschied: Vollständiger Leitfaden (2026)",
    "utc8toutc5.meta.title": "UTC+8 zu UTC-5 Konverter (2026): Vollständige 24-Stunden-Tabelle & globale Besprechungszeiten",
    "utc8toutc5.meta.desc": "UTC+8 (China) sofort in UTC-5 (US-Ostküste) umrechnen. 24-Stunden-Tabelle, Sommerzeit 2026, beste Anrufzeiten & typische Fehler.",
    "utc8toutc5.h1": "🌏 UTC+8 zu UTC-5 Konverter",
    "utctocstconverter.meta.title": "UTC zu CST Konverter - Weltzeit nach China Standard Time | GlobeTimeZone",
    "utctocstconverter.meta.desc": "UTC sofort in CST (China Standard Time) umrechnen. UTC-zu-Peking/Shanghai-Konverter mit 24-Stunden-Tabelle und Sommerzeit-Info.",
    "utctocstconverter.h1": "🕐 UTC zu CST Konverter",
    "whydaylightsavingtime.meta.title": "Warum gibt es die Sommerzeit? Ein vollständiger Leitfaden | GlobeTimeZone",
    "whydaylightsavingtime.meta.desc": "Entdecken Sie die Geschichte und Gründe der Sommerzeit. Warum stellen wir die Uhren zweimal im Jahr um? Welche Länder verwenden noch Sommerzeit? Lesen Sie unseren vollständigen Leitfaden.",
    "whydaylightsavingtime.h1": "Warum gibt es die Sommerzeit?",
    "worldclock.meta.title": "Weltuhr - Live-Zeit in allen großen Städten | GlobeTimeZone",
    "worldclock.meta.desc": "Live-Weltuhr zeigt die aktuelle Zeit in allen großen Städten weltweit. Echtzeit-Uhr mit automatischen Sommerzeit-Updates. Zeiten über New York, London, Tokyo, Sydney und mehr vergleichen.",
    "worldclock.h1": "🌐 Weltuhr",
    "worldmap.meta.title": "Interaktive Weltzeitzonenkarte | GlobeTimeZone",
    "worldmap.meta.desc": "Interaktive Weltzeitzonenkarte. Klicken Sie auf Regionen, um Zeiten weltweit zu vergleichen. Perfekt zum Verständnis globaler Zeitunterschiede.",
    "worldmap.h1": "🗺️ Weltzeitzonenkarte",
}

# =============================================================================
# FRANÇAIS (fr)
# =============================================================================
fr = {
    "meta.title": "GlobeTimeZone — Outil de décision temporelle mondiale",
    "meta.description": "Savoir instantanément s'il faut contacter ou planifier une réunion. Ressentir le rythme mondial en temps réel.",
    "nav.skipToContent": "Aller au contenu principal",
    "nav.ariaLabel": "Navigation principale",
    "nav.timezones": "Fuseaux horaires",
    "nav.meeting": "Planificateur de réunion",
    "nav.crossborder": "Transfrontalier",
    "nav.guides": "Guides",
    "nav.upgrade": "Passer PRO",
    "nav.langButton": "🌐 Français ▾",
    "nav.langButtonAriaLabel": "Changer de langue",
    "hero.badge": "🌏 En ce moment dans le monde",
    "hero.title": "Savoir l'heure qu'il est,<br>partout. Instantanément.",
    "hero.subtitle": "San Francisco dort. Londres commence sa journée. Tokyo entre dans le soir.<br>Pas de calcul mental, pas de conversion — ressentez le rythme mondial en un coup d'œil.",
    "hero.search.placeholder": "Rechercher une ville… Tokyo, Londres, New York, Paris…",
    "hero.search.button": "🔍 Rechercher",
    "hero.city.placeholder": "Ajouter une ville au tableau…",
    "hero.city.button": "+ Ajouter",
    "footer.about": "À propos",
    "footer.privacy": "Confidentialité",
    "footer.terms": "Conditions d'utilisation",
    "footer.contact": "Contact",
    "footer.copyright": "© 2026 GlobeTimeZone · Toutes les données horaires calibrées via NTP · Données de fuseaux horaires via IANA",
    "about.meta.title": "À propos de GlobeTimeZone – Notre histoire et mission",
    "about.meta.desc": "Découvrez GlobeTimeZone.",
    "about.h1": "Notre histoire",
    "apiguide.meta.title": "Guide API des fuseaux horaires pour développeurs : Conversion programmatique | GlobeTimeZone",
    "apiguide.meta.desc": "Guide complet des API de fuseaux horaires. Convertir les heures, détecter l'heure d'été et gérer les fuseaux horaires dans vos applications. Comparer les API publiques, exemples de code JavaScript, Python et plus.",
    "apiguide.h1": "Guide API des fuseaux horaires pour développeurs : Conversion programmatique",
    "api.meta.title": "API GlobeTimeZone - API gratuite de données et conversion de fuseaux horaires | Documentation",
    "api.meta.desc": "API gratuite de conversion de fuseaux horaires, heure actuelle et données de fuseaux. Endpoints RESTful avec réponses JSON. Aucune clé API requise pour la version de base. Intégrez l'heure mondiale dans vos applications.",
    "api.h1": "⚡ API GlobeTimeZone",
    "articles.meta.title": "Articles et guides sur les fuseaux horaires – GlobeTimeZone.com",
    "articles.meta.desc": "Tout savoir sur les fuseaux horaires, l'heure d'été, UTC et comment gérer les décalages horaires pour les affaires et les voyages.",
    "articles.h1": "📖 Articles et guides sur les fuseaux horaires",
    "asttopst.meta.title": "Convertisseur AST vers PST (2026) : Tableau complet & heures de réunion Caraïbes-Ouest US",
    "asttopst.meta.desc": "Convertir rapidement l'heure normale de l'Atlantique en heure du Pacifique. Tableau 24h, dates d'heure d'été 2026, meilleurs créneaux d'appel et conseils pratiques.",
    "asttopst.h1": "🏝️ Convertisseur AST vers PST",
    "cettoest.meta.title": "Convertisseur CET vers EST (2026) : Tableau complet & heures de réunion Europe-US",
    "cettoest.meta.desc": "Convertir rapidement l'heure d'Europe centrale en heure de la côte est des États-Unis. Tableau 24h, changements d'heure d'été 2026, meilleurs créneaux et erreurs courantes.",
    "cettoest.h1": "🏰 Convertisseur CET vers EST",
    "contact.meta.title": "Contactez-nous – GlobeTimeZone",
    "contact.meta.desc": "Contactez GlobeTimeZone. Questions, retours, partenariats ou demandes commerciales.",
    "contact.h1": "📬 Contactez-nous",
    "countdown.meta.title": "Minuteur de compte à rebours - Compte à rebours multi-fuseaux horaires | GlobeTimeZone",
    "countdown.meta.desc": "Créez des comptes à rebours d'événements et visualisez-les dans plusieurs fuseaux horaires simultanément. Parfait pour les célébrations d'équipes mondiales, les lancements de produits et les échéances internationales.",
    "countdown.h1": "⏱️ Minuteur de compte à rebours",
    "disclaimer.meta.title": "Avertissement – GlobeTimeZone.com",
    "disclaimer.h1": "Avertissement",
    "distributedteamtimeculture.meta.title": "Comment les équipes distribuées peuvent construire une culture du « respect du temps » | GlobeTimeZone",
    "distributedteamtimeculture.meta.desc": "Stratégies pratiques pour construire une culture respectueuse du temps dans les équipes distribuées. Établir des heures d'ancrage, prioriser la communication asynchrone et utiliser les outils de fuseaux horaires pour prévenir l'épuisement.",
    "distributedteamtimeculture.h1": "Comment les équipes distribuées peuvent construire une culture du « respect du temps »",
    "dst2025schedule.meta.title": "Calendrier mondial de l'heure d'été 2025 & dates | GlobeTimeZone",
    "dst2025schedule.meta.desc": "Calendrier complet de l'heure d'été 2025 : dates de début et de fin pour les États-Unis, le Royaume-Uni, l'UE, l'Australie, la Nouvelle-Zélande et plus. Ne ratez plus aucun changement d'heure.",
    "dst2025schedule.h1": "Calendrier mondial de l'heure d'été 2025 : dates de début et de fin complètes",
    "embedwidget.meta.title": "Widget d'horloge mondiale intégrable gratuit | GlobeTimeZone",
    "embedwidget.meta.desc": "Ajoutez un widget d'horloge mondiale gratuit à votre site web. Villes personnalisables, thème clair/sombre, compact ou complet. Copiez le code d'intégration en quelques secondes.",
    "embedwidget.h1": "🆓 Widget d'horloge mondiale gratuit",
    "esttocstconverter.meta.title": "Convertisseur EST vers CST - Heure de l'Est au Centre | GlobeTimeZone",
    "esttocstconverter.meta.desc": "Convertir instantanément EST (Eastern Standard Time) en CST (Central Standard Time). Convertisseur gratuit avec tableau 24h et conseils de réunion.",
    "esttocstconverter.h1": "🕐 Convertisseur EST vers CST",
    "esttopstconverter.meta.title": "Convertisseur EST vers PST - Heure de l'Est au Pacifique | GlobeTimeZone",
    "esttopstconverter.meta.desc": "Convertir instantanément EST (Eastern Standard Time) en PST (Pacific Standard Time). Convertisseur gratuit avec tableau 24h. Décalage de 3 heures.",
    "esttopstconverter.h1": "🕐 Convertisseur EST vers PST",
    "europeaustraliatimedifference.meta.title": "Décalage horaire Europe vs Australie (2026) : Tableau 24h complet & meilleures heures de réunion",
    "europeaustraliatimedifference.meta.desc": "Comparez instantanément les fuseaux horaires de l'Europe et de l'Australie. Tableau de conversion complet, décalages d'heure d'été hémisphères opposés, meilleurs créneaux et erreurs courantes.",
    "europeaustraliatimedifference.h1": "🦘 Convertisseur d'heure Europe vers Australie",
    "gmttocstconverter.meta.title": "Convertisseur GMT vers CST - Greenwich à l'heure standard de Chine | GlobeTimeZone",
    "gmttocstconverter.meta.desc": "Convertir instantanément GMT (Greenwich Mean Time) en CST (China Standard Time). Convertisseur gratuit avec tableau 24h et affichage des heures de travail.",
    "gmttocstconverter.h1": "🕐 Convertisseur GMT vers CST",
    "hawaiitoest.meta.title": "Convertisseur Hawaï vers EST (2026) : Tableau complet & meilleures heures de réunion US",
    "hawaiitoest.meta.desc": "Convertir rapidement l'heure d'Hawaï-Aléoutiennes en heure de la côte est des États-Unis. Tableau 24h, règles d'heure d'été 2026, meilleurs créneaux et erreurs courantes.",
    "hawaiitoest.h1": "🌺 Convertisseur Hawaï vers EST",
    "holidays.meta.title": "Jours fériés mondiaux 2026 - Jours fériés dans 200+ pays | GlobeTimeZone",
    "holidays.meta.desc": "Consultez les jours fériés et observances dans 200+ pays. Parfait pour la planification commerciale internationale, les voyages et la sensibilisation culturelle.",
    "holidays.h1": "🎉 Jours fériés mondiaux 2026",
    "isttoestconverter.meta.title": "Convertisseur IST vers EST | Inde à l'heure de l'Est | GlobeTimeZone",
    "isttoestconverter.meta.desc": "Convertir IST (India Standard Time, UTC+5:30) en EST (Eastern Standard Time, UTC-5). Convertisseur interactif, tableau 24h et meilleures heures de réunion Inde-côte est US.",
    "isttoestconverter.h1": "Convertisseur d'heure IST vers EST",
    "jsttocstconverter.meta.title": "Convertisseur JST vers CST - Japon à l'heure standard de Chine | GlobeTimeZone",
    "jsttocstconverter.meta.desc": "Convertir instantanément JST (Japan Standard Time) en CST (China Standard Time). Convertisseur gratuit. Le Japon et la Chine partagent le même décalage UTC+8.",
    "jsttocstconverter.h1": "🕐 Convertisseur JST vers CST",
    "meetingscheduler.meta.title": "Planificateur de réunion - Trouver les meilleures heures de réunion inter-fuseaux | GlobeTimeZone",
    "meetingscheduler.meta.desc": "Planificateur de réunion intelligent gratuit. Trouvez les meilleures heures de réunion dans plusieurs fuseaux horaires. Planification d'équipe avec affichage des heures de travail.",
    "meetingscheduler.h1": "📅 Planificateur de réunion",
    "privacypolicy.meta.title": "Politique de confidentialité - GlobeTimeZone",
    "privacypolicy.h1": "🔒 Politique de confidentialité",
    "privacy.meta.title": "Politique de confidentialité – GlobeTimeZone",
    "privacy.meta.desc": "Politique de confidentialité GlobeTimeZone. Nous ne vendons pas vos données.",
    "privacy.h1": "Politique de confidentialité",
    "pro.meta.title": "GlobeTimeZone Pro - Fonctionnalités premium pour utilisateurs avancés",
    "pro.meta.desc": "Passez à GlobeTimeZone Pro pour des horloges illimitées, une expérience sans publicité, un accès API et un support prioritaire.",
    "pro.h1": "🚀 GlobeTimeZone Pro",
    "psttocstconverter.meta.title": "Convertisseur PST vers CST | Pacifique à l'heure standard de Chine | GlobeTimeZone",
    "psttocstconverter.meta.desc": "Convertir PST (Pacific Standard Time, UTC-8) en CST (China Standard Time, UTC+8). Tableau 24h, convertisseur rapide et meilleures heures pour les appels Californie-Chine.",
    "psttocstconverter.h1": "Convertisseur d'heure PST vers CST (Chine)",
    "psttoest.meta.title": "Convertisseur PST vers EST (2026) : Tableau complet & meilleures heures de réunion trans-US",
    "psttoest.meta.desc": "Convertir rapidement l'heure du Pacifique en heure de l'Est. Tableau 24h, dates d'heure d'été 2026, meilleurs créneaux et erreurs de fuseaux horaires courantes.",
    "psttoest.h1": "🗼 Convertisseur PST vers EST",
    "remoteteamtimezoneguide.meta.title": "Guide de gestion des fuseaux horaires pour équipes à distance | GlobeTimeZone",
    "remoteteamtimezoneguide.meta.desc": "Guide complet pour gérer des équipes à distance à travers les fuseaux horaires. Planifier les réunions, maintenir la productivité et construire la culture dans les équipes distribuées.",
    "remoteteamtimezoneguide.h1": "🤝 Guide de gestion des fuseaux horaires pour équipes à distance",
    "remoteteamtimezonetools.meta.title": "Comparatif des meilleurs outils de fuseaux horaires pour équipes à distance : Guide 2025 | GlobeTimeZone",
    "remoteteamtimezonetools.meta.desc": "Comparez les meilleurs outils de fuseaux horaires pour équipes à distance : Slack, Google Calendar, World Time Buddy, Clockwise et plus. Choisissez le bon outil pour votre équipe distribuée.",
    "remoteteamtimezonetools.h1": "Comparatif des meilleurs outils de fuseaux horaires pour équipes à distance : Guide complet 2025",
    "remoteworktimezone.meta.title": "Travail à distance et guide des fuseaux horaires pour équipes mondiales | GlobeTimeZone",
    "remoteworktimezone.meta.desc": "Comment gérer les fuseaux horaires dans une équipe à distance ou distribuée. Bonnes pratiques pour planifier les réunions, définir les heures de base et éviter la fatigue des fuseaux horaires.",
    "remoteworktimezone.h1": "Le manuel complet des fuseaux horaires pour équipes à distance",
    "subscribe.meta.title": "S'abonner à GlobeTimeZone - Conseils et mises à jour hebdomadaires sur les fuseaux horaires",
    "subscribe.meta.desc": "Abonnez-vous à GlobeTimeZone pour des conseils et mises à jour sur les fuseaux horaires.",
    "subscribe.h1": "📬 Restez synchronisé avec GlobeTimeZone",
    "teamoverlap.meta.title": "Calculateur de chevauchement horaire d'équipe - Trouver les heures de travail communes | GlobeTimeZone",
    "teamoverlap.meta.desc": "Trouvez les heures de travail chevauchantes pour votre équipe à distance à travers les fuseaux horaires. Panneau visuel pour voir quand tout le monde est disponible. Parfait pour les équipes distribuées.",
    "teamoverlap.h1": "👥 Calculateur de chevauchement horaire d'équipe",
    "terms.meta.title": "Conditions d'utilisation – GlobeTimeZone",
    "terms.meta.desc": "Conditions d'utilisation GlobeTimeZone. Notre outil est gratuit pour un usage personnel et commercial.",
    "terms.h1": "Conditions d'utilisation",
    "timedifference.chicagototokyo.meta.title": "Décalage horaire entre Chicago et Tokyo (2026)",
    "timedifference.chicagototokyo.meta.desc": "Chicago à Tokyo : le cœur de l'Amérique rencontre le Japon à travers 14-15 heures. Comparaison complète, meilleurs créneaux d'appel et retours d'expérience.",
    "timedifference.chicagototokyo.h1": "Décalage horaire entre Chicago et Tokyo (2026) : Le cœur de l'Amérique rencontre le Japon",
    "timedifference.dubaitolosangeles.meta.title": "Décalage horaire entre Dubaï et Los Angeles (2026) : Guide complet",
    "timedifference.dubaitolosangeles.meta.desc": "Dubaï à LA couvre 12-13 heures sans chevauchement d'heures de travail. Guide complet de planification avec stratégies de flexibilité asymétrique.",
    "timedifference.dubaitolosangeles.h1": "Décalage horaire entre Dubaï et Los Angeles (2026) : Du Golfe au Pacifique",
    "timedifference.frankfurttonewyork.meta.title": "Décalage horaire entre Francfort et New York (2026) : Guide financier",
    "timedifference.frankfurttonewyork.meta.desc": "Francfort et New York animent les marchés financiers mondiaux. Comparaison complète, fenêtres de trading et retours d'expérience.",
    "timedifference.frankfurttonewyork.h1": "Décalage horaire entre Francfort et New York (2026) : La finance européenne rencontre les marchés américains",
    "timedifference.hongkongtolosangeles.meta.title": "Décalage horaire entre Hong Kong et Los Angeles (2026) : Guide complet",
    "timedifference.hongkongtolosangeles.meta.desc": "Hong Kong à LA traverse le Pacifique avec 15-16 heures de décalage. Guide complet, meilleurs créneaux et retours d'expérience.",
    "timedifference.hongkongtolosangeles.h1": "Décalage horaire entre Hong Kong et Los Angeles (2026) : Le cœur financier de l'Asie rencontre Hollywood",
    "timedifference.latobeijing.meta.title": "Décalage horaire entre Los Angeles et Pékin (2026) : Travailler à travers le Pacifique",
    "timedifference.latobeijing.meta.desc": "Planifier des appels entre LA et Pékin ? L'écart de 15-16 heures signifie qu'une partie travaille toujours en dehors des heures ouvrables. Stratégies de planification complètes.",
    "timedifference.latobeijing.h1": "Décalage horaire entre Los Angeles et Pékin (2026) : Travailler à travers le Pacifique",
    "timedifference.miamitolondon.meta.title": "Décalage horaire entre Miami et Londres (2026)",
    "timedifference.miamitolondon.meta.desc": "Miami à Londres : le soleil rencontre le brouillard à travers 5-7 heures. Comparaison complète, meilleurs créneaux et retours d'expérience.",
    "timedifference.miamitolondon.h1": "Décalage horaire entre Miami et Londres (2026) : Le soleil rencontre le brouillard",
    "timedifference.mumbaitodubai.meta.title": "Décalage horaire entre Mumbai et Dubaï (2026)",
    "timedifference.mumbaitodubai.meta.desc": "Mumbai à Dubaï : l'Asie du Sud rencontre le Golfe à travers seulement 1,5 heure. Comparaison complète et meilleurs créneaux d'appel.",
    "timedifference.mumbaitodubai.h1": "Décalage horaire entre Mumbai et Dubaï (2026) : Voisins proches",
    "timedifference.newyorktolondon.meta.title": "Décalage horaire entre New York et Londres (2026) : Guide complet finance, tech & business",
    "timedifference.newyorktolondon.meta.desc": "Décalage horaire New York-Londres expliqué : 4-5 heures selon l'heure d'été. Fenêtres finance/trading, tips réunions tech, dates heure d'été 2026 et convertisseur gratuit. Guide expert.",
    "timedifference.newyorktolondon.h1": "Décalage horaire entre New York et Londres (2026) : Le guide complet business & finance",
    "timedifference.nuevayorkalondres.meta.title": "Décalage horaire entre New York et Londres (2026) : Convertisseur et meilleures heures de réunion",
    "timedifference.nuevayorkalondres.meta.desc": "Convertir instantanément l'heure entre New York et Londres avec notre outil gratuit. Règles heure d'été 2026, meilleures heures de réunion et erreurs courantes.",
    "timedifference.nuevayorkalondres.h1": "Décalage horaire entre New York et Londres (2026) : Convertisseur complet et meilleures heures",
    "timedifference.paristonewyork.meta.title": "Décalage horaire entre Paris et New York (2026) : Guide complet",
    "timedifference.paristonewyork.meta.desc": "Paris-New York est l'une des routes transatlantiques les plus faciles — jusqu'à ce que l'heure d'été vous surprenne. Comparaison complète et pièges courants.",
    "timedifference.paristonewyork.h1": "Décalage horaire entre Paris et New York (2026) : La route presque facile",
    "timedifference.seoultolondon.meta.title": "Décalage horaire entre Séoul et Londres (2026)",
    "timedifference.seoultolondon.meta.desc": "Séoul à Londres : la culture K rencontre la tradition britannique à travers 8-9 heures. Comparaison complète, meilleurs créneaux et retours d'expérience.",
    "timedifference.seoultolondon.h1": "Décalage horaire entre Séoul et Londres (2026) : La capitale de la culture K rencontre la Grande-Bretagne",
    "timedifference.singaporetolondon.meta.title": "Décalage horaire entre Singapour et Londres (2026)",
    "timedifference.singaporetolondon.meta.desc": "Singapour à Londres couvre 7-8 heures à travers les continents. Retours d'expérience pour gérer les appels entre la Cité-Lion et la City of London, avec tips finance et trading.",
    "timedifference.singaporetolondon.h1": "Décalage horaire entre Singapour et Londres (2026) : Le guide business complet",
    "timedifference.sydneytolondon.meta.title": "Décalage horaire entre Sydney et Londres (2026) : Guide complet",
    "timedifference.sydneytolondon.meta.desc": "Sydney à Londres couvre près de 17 000 km avec des chevauchements d'heure d'été complexes. Années d'expérience sur cette route, y compris les stratégies de planification.",
    "timedifference.sydneytolondon.h1": "Décalage horaire entre Sydney et Londres (2026) : Naviguer entre hémisphères opposés",
    "timedifference.sydneytonewyork.meta.title": "Décalage horaire entre Sydney et New York (2026)",
    "timedifference.sydneytonewyork.meta.desc": "Sydney à New York : hémisphères opposés, écart de 14-19 heures. Comparaison complète, meilleurs créneaux et retours d'expérience.",
    "timedifference.sydneytonewyork.h1": "Décalage horaire entre Sydney et New York (2026) : Hémisphères opposés",
    "timedifference.tokyotonewyork.meta.title": "Décalage horaire entre Tokyo et New York (2026) : Le guide ultime business & voyage",
    "timedifference.tokyotonewyork.meta.desc": "Guide complet Tokyo-New York : décalage de 13-14 heures expliqué. Planificateur de réunions, dates heure d'été 2026, tips par secteur finance, tech & divertissement. Convertisseur gratuit inclus.",
    "timedifference.tokyotonewyork.h1": "Décalage horaire entre Tokyo et New York (2026) : Le guide complet business & voyage",
    "timedifference.torontotoshanghai.meta.title": "Décalage horaire entre Toronto et Shanghai (2026) : Guide complet",
    "timedifference.torontotoshanghai.meta.desc": "Toronto-Shanghai n'a aucun chevauchement d'heures de travail — l'écart de 12-13 heures signifie que quelqu'un doit toujours être en ligne en dehors des heures ouvrables. Stratégies de planification complètes.",
    "timedifference.torontotoshanghai.h1": "Décalage horaire entre Toronto et Shanghai (2026) : Gérer la route sans chevauchement",
    "timedifference.洛杉矶到北京.meta.title": "Décalage horaire entre Los Angeles et Pékin (2026) : Tableau complet et meilleures heures d'appel",
    "timedifference.洛杉矶到北京.meta.desc": "Consultez le décalage exact entre LA et Pékin, le tableau de conversion 24h, les règles d'heure d'été 2026 et les meilleures heures pour les appels business transpacifiques.",
    "timedifference.洛杉矶到北京.h1": "Décalage horaire entre Los Angeles et Pékin (2026) : Tableau complet et meilleures heures d'appel",
    "timein.beijing.meta.title": "Heure actuelle à Pékin | Fuseau horaire, date | GlobeTimeZone",
    "timein.beijing.meta.desc": "Consultez l'heure actuelle à Pékin, Chine. Heure exacte, date, décalage de fuseau horaire (CST, UTC+8). Pas d'heure d'été. Comparez avec d'autres villes dans le monde.",
    "timein.beijing.h1": "Heure actuelle à Pékin",
    "timein.chicago.meta.title": "Heure actuelle à Chicago | Fuseau CST/CDT | GlobeTimeZone",
    "timein.chicago.meta.desc": "Consultez l'heure actuelle à Chicago, Illinois. Horloge en direct, CST/CDT heure du Centre (UTC-6/UTC-5), état de l'heure d'été et comparaison avec les grandes villes du monde.",
    "timein.chicago.h1": "Heure actuelle à Chicago",
    "timein.dubai.meta.title": "Heure actuelle à Dubaï | GST (UTC+4) | GlobeTimeZone",
    "timein.dubai.meta.desc": "Consultez l'heure actuelle à Dubaï, EAU. Horloge en direct, fuseau GST (UTC+4), pas d'heure d'été. Comparez l'heure de Dubaï avec d'autres villes.",
    "timein.dubai.h1": "Heure actuelle à Dubaï",
    "timein.london.meta.title": "Heure actuelle à Londres | Fuseau horaire, date | GlobeTimeZone",
    "timein.london.meta.desc": "Consultez l'heure actuelle à Londres, Royaume-Uni. Heure exacte, date, décalage de fuseau horaire (GMT/BST), heures de lever et coucher du soleil. Comparez avec d'autres villes.",
    "timein.london.h1": "Heure actuelle à Londres",
    "timein.losangeles.meta.title": "Heure actuelle à Los Angeles | PST/PDT | GlobeTimeZone",
    "timein.losangeles.meta.desc": "Consultez l'heure actuelle à Los Angeles, Californie. Horloge en direct, PST/PDT heure du Pacifique (UTC-8/UTC-7), état de l'heure d'été et comparaison mondiale.",
    "timein.losangeles.h1": "Heure actuelle à Los Angeles",
    "timein.newyork.meta.title": "Heure actuelle à New York | Fuseau horaire, date | GlobeTimeZone",
    "timein.newyork.meta.desc": "Consultez l'heure actuelle à New York, États-Unis. Heure exacte, date, décalage de fuseau horaire (EST/EDT). Comparez avec d'autres villes dans le monde.",
    "timein.newyork.h1": "Heure actuelle à New York",
    "timein.paris.meta.title": "Heure actuelle à Paris | CET/CEST | GlobeTimeZone",
    "timein.paris.meta.desc": "Consultez l'heure actuelle à Paris, France. Horloge en direct, date, décalage CET/CEST, état de l'heure d'été. Comparez l'heure de Paris avec d'autres villes.",
    "timein.paris.h1": "Heure actuelle à Paris",
    "timein.seoul.meta.title": "Heure actuelle à Séoul | KST (UTC+9) | GlobeTimeZone",
    "timein.seoul.meta.desc": "Consultez l'heure actuelle à Séoul, Corée du Sud. Horloge en direct, fuseau KST (UTC+9), pas d'heure d'été, comparaison avec Pékin, Tokyo et New York.",
    "timein.seoul.h1": "Heure actuelle à Séoul",
    "timein.singapore.meta.title": "Heure actuelle à Singapour | SGT (UTC+8) | GlobeTimeZone",
    "timein.singapore.meta.desc": "Consultez l'heure actuelle à Singapour. Horloge en direct, fuseau SGT (UTC+8), pas d'heure d'été. Comparez avec Londres, New York, Pékin et plus.",
    "timein.singapore.h1": "Heure actuelle à Singapour",
    "timein.sydney.meta.title": "Heure actuelle à Sydney | AEDT/AEST | GlobeTimeZone",
    "timein.sydney.meta.desc": "Consultez l'heure actuelle à Sydney, Australie. Horloge en direct, AEDT/AEST (UTC+11/UTC+10), état de l'heure d'été et comparaison mondiale.",
    "timein.sydney.h1": "Heure actuelle à Sydney",
    "timein.tokyo.meta.title": "Heure actuelle à Tokyo | Fuseau horaire, date | GlobeTimeZone",
    "timein.tokyo.meta.desc": "Consultez l'heure actuelle à Tokyo, Japon. Heure exacte, date, décalage de fuseau horaire (JST, UTC+9). Pas d'heure d'été. Comparez avec d'autres villes dans le monde.",
    "timein.tokyo.h1": "Heure actuelle à Tokyo",
    "timein.toronto.meta.title": "Heure actuelle à Toronto | EST/EDT | GlobeTimeZone",
    "timein.toronto.meta.desc": "Consultez l'heure actuelle à Toronto, Canada. Horloge en direct, EST/EDT heure de l'Est (UTC-5/UTC-4), état de l'heure d'été et comparaison mondiale.",
    "timein.toronto.h1": "Heure actuelle à Toronto",
    "timeunits.meta.title": "Convertisseur d'unités de temps - Heures, minutes, secondes, temps décimal | GlobeTimeZone",
    "timeunits.meta.desc": "Convertisseur d'unités de temps gratuit. Convertir entre heures, minutes, secondes, heures décimales et plus. Parfait pour la paie, la gestion de projet et le suivi du temps.",
    "timeunits.h1": "🔄 Convertisseur d'unités de temps",
    "timestampevidence.meta.title": "GlobeTimeZone - Preuve d'horodatage numérique",
    "timestampevidence.meta.desc": "Preuve d'horodatage numérique de haute fiabilité - Conforme à la loi sur les signatures électroniques",
    "timestampevidence.h1": "Certificat d'horodatage numérique haute fiabilité GlobeTimeZone",
    "timezoneguide.meta.title": "Guide complet des fuseaux horaires mondiaux | GlobeTimeZone",
    "timezoneguide.meta.desc": "Tout ce que vous devez savoir sur les fuseaux horaires mondiaux : décalages UTC, fonctionnement, la base de données IANA, UTC vs GMT et conseils de planification inter-fuseaux.",
    "timezoneguide.h1": "Guide complet des fuseaux horaires mondiaux",
    "timezonehistory.meta.title": "Histoire fascinante des fuseaux horaires : La ligne de changement de date, le jour perdu des Samoa et plus | GlobeTimeZone",
    "timezonehistory.meta.desc": "Découvrez les histoires les plus fascinantes de l'histoire des fuseaux horaires : comment la ligne de changement de date a été créée, pourquoi les Samoa ont sauté un jour, le chaos du temps ferroviaire et la politique de l'UTC.",
    "timezonehistory.h1": "Histoire fascinante des fuseaux horaires : La ligne de date, les jours perdus et le chaos ferroviaire",
    "uschinatimedifference.meta.title": "Décalage horaire États-Unis vs Chine – GlobeTimeZone.com",
    "uschinatimedifference.meta.desc": "Quel est le décalage horaire entre les États-Unis et la Chine ? Guide complet des fuseaux horaires américano-chinois, heure d'été et meilleures heures d'appel.",
    "uschinatimedifference.h1": "Décalage horaire États-Unis vs Chine : Guide complet (2026)",
    "utc8toutc5.meta.title": "Convertisseur UTC+8 vers UTC-5 (2026) : Tableau 24h complet & heures de réunion mondiales",
    "utc8toutc5.meta.desc": "Convertir instantanément UTC+8 (Chine) en UTC-5 (Est des États-Unis). Tableau 24h, changements heure d'été 2026, meilleurs créneaux et erreurs courantes.",
    "utc8toutc5.h1": "🌏 Convertisseur UTC+8 vers UTC-5",
    "utctocstconverter.meta.title": "Convertisseur UTC vers CST - Temps universel à l'heure standard de Chine | GlobeTimeZone",
    "utctocstconverter.meta.desc": "Convertir instantanément UTC en CST (heure standard de Chine). Convertisseur UTC-Pékin/Shanghai avec tableau 24h et infos heure d'été.",
    "utctocstconverter.h1": "🕐 Convertisseur UTC vers CST",
    "whydaylightsavingtime.meta.title": "Pourquoi l'heure d'été existe-t-elle ? Guide complet | GlobeTimeZone",
    "whydaylightsavingtime.meta.desc": "Découvrez l'histoire et les raisons de l'heure d'été. Pourquoi changeons-nous d'heure deux fois par an ? Quels pays utilisent encore l'heure d'été ? Lisez notre guide complet.",
    "whydaylightsavingtime.h1": "Pourquoi l'heure d'été existe-t-elle ?",
    "worldclock.meta.title": "Horloge mondiale - Heure en direct dans toutes les grandes villes | GlobeTimeZone",
    "worldclock.meta.desc": "Horloge mondiale en direct affichant l'heure actuelle dans toutes les grandes villes du monde. Mises à jour automatiques de l'heure d'été. Comparez New York, Londres, Tokyo, Sydney et plus.",
    "worldclock.h1": "🌐 Horloge mondiale",
    "worldmap.meta.title": "Carte interactive des fuseaux horaires mondiaux | GlobeTimeZone",
    "worldmap.meta.desc": "Carte interactive des fuseaux horaires mondiaux. Cliquez sur les régions pour comparer les heures dans le monde. Parfait pour comprendre les décalages horaires globaux.",
    "worldmap.h1": "🗺️ Carte des fuseaux horaires mondiaux",
}

# =============================================================================
# ESPAÑOL (es)
# =============================================================================
es = {
    "meta.title": "GlobeTimeZone — Herramienta de decisión horaria global",
    "meta.description": "Saber al instante si contactar o programar una reunión. Sentir el ritmo global en tiempo real.",
    "nav.skipToContent": "Ir al contenido principal",
    "nav.ariaLabel": "Navegación principal",
    "nav.timezones": "Zonas horarias",
    "nav.meeting": "Planificador de reuniones",
    "nav.crossborder": "Transfronterizo",
    "nav.guides": "Guías",
    "nav.upgrade": "Mejorar a PRO",
    "nav.langButton": "🌐 Español ▾",
    "nav.langButtonAriaLabel": "Cambiar idioma",
    "hero.badge": "🌏 Ahora mismo en el mundo",
    "hero.title": "Saber la hora,<br>en cualquier lugar. Al instante.",
    "hero.subtitle": "San Francisco duerme. Londres empieza a trabajar. Tokio se prepara para el atardecer.<br>Sin cálculos mentales, sin conversiones — siente el ritmo global de un vistazo.",
    "hero.search.placeholder": "Buscar cualquier ciudad… Tokio, Londres, Nueva York, París…",
    "hero.search.button": "🔍 Buscar",
    "hero.city.placeholder": "Añadir una ciudad al panel…",
    "hero.city.button": "+ Añadir",
    "footer.about": "Sobre nosotros",
    "footer.privacy": "Privacidad",
    "footer.terms": "Términos de servicio",
    "footer.contact": "Contacto",
    "footer.copyright": "© 2026 GlobeTimeZone · Todos los datos horarios calibrados vía NTP · Datos de zonas horarias vía IANA",
    "about.meta.title": "Sobre GlobeTimeZone – Nuestra historia y misión",
    "about.meta.desc": "Conoce GlobeTimeZone.",
    "about.h1": "Nuestra historia",
    "apiguide.meta.title": "Guía de API de zonas horarias para desarrolladores: Conversión programática | GlobeTimeZone",
    "apiguide.meta.desc": "Guía completa de APIs de zonas horarias. Aprende a convertir horas, detectar el horario de verano y gestionar zonas horarias en tus aplicaciones. Compara APIs públicas, ejemplos de código JavaScript, Python y más.",
    "apiguide.h1": "Guía de API de zonas horarias para desarrolladores: Conversión programática",
    "api.meta.title": "API GlobeTimeZone - API gratuita de datos y conversión de zonas horarias | Documentación",
    "api.meta.desc": "API gratuita de conversión de zonas horarias, hora actual y datos de zonas. Endpoints RESTful con respuestas JSON. No se necesita clave API para la versión básica. Integra la hora mundial en tus aplicaciones.",
    "api.h1": "⚡ API GlobeTimeZone",
    "articles.meta.title": "Artículos y guías sobre zonas horarias – GlobeTimeZone.com",
    "articles.meta.desc": "Aprende sobre zonas horarias, horario de verano, UTC y cómo gestionar las diferencias horarias para negocios y viajes.",
    "articles.h1": "📖 Artículos y guías sobre zonas horarias",
    "asttopst.meta.title": "Convertidor AST a PST (2026): Tabla completa y horarios de reuniones Caribe-Oeste US",
    "asttopst.meta.desc": "Convierte rápidamente la Hora Estándar del Atlántico a la Hora del Pacífico. Tabla 24h, fechas de horario de verano 2026, mejores ventanas de llamada y consejos prácticos.",
    "asttopst.h1": "🏝️ Convertidor AST a PST",
    "cettoest.meta.title": "Convertidor CET a EST (2026): Tabla completa y horarios de reuniones Europa-US",
    "cettoest.meta.desc": "Convierte rápidamente la Hora de Europa Central a la Hora del Este de EE.UU. Tabla 24h, cambios de horario de verano 2026, mejores ventanas y errores comunes.",
    "cettoest.h1": "🏰 Convertidor CET a EST",
    "contact.meta.title": "Contáctenos – GlobeTimeZone",
    "contact.meta.desc": "Póngase en contacto con GlobeTimeZone. Preguntas, comentarios, asociaciones o consultas comerciales.",
    "contact.h1": "📬 Contáctenos",
    "countdown.meta.title": "Temporizador de cuenta regresiva - Cuenta regresiva en múltiples zonas horarias | GlobeTimeZone",
    "countdown.meta.desc": "Crea cuentas regresivas de eventos y míralas en múltiples zonas horarias simultáneamente. Perfecto para celebraciones de equipos globales, lanzamientos de productos y plazos internacionales.",
    "countdown.h1": "⏱️ Temporizador de cuenta regresiva",
    "disclaimer.meta.title": "Aviso legal – GlobeTimeZone.com",
    "disclaimer.h1": "Aviso legal",
    "distributedteamtimeculture.meta.title": "Cómo los equipos distribuidos pueden construir una cultura de \"respeto del tiempo\" | GlobeTimeZone",
    "distributedteamtimeculture.meta.desc": "Aprende estrategias prácticas para construir una cultura respetuosa del tiempo en equipos distribuidos. Cómo establecer horas de anclaje, priorizar la comunicación asíncrona y usar herramientas de zonas horarias para prevenir el agotamiento.",
    "distributedteamtimeculture.h1": "Cómo los equipos distribuidos pueden construir una cultura de \"respeto del tiempo\"",
    "dst2025schedule.meta.title": "Calendario mundial del horario de verano 2025 y fechas | GlobeTimeZone",
    "dst2025schedule.meta.desc": "Calendario completo del horario de verano 2025: fechas de inicio y fin para EE.UU., Reino Unido, UE, Australia, Nueva Zelanda y más. No te pierdas ningún cambio de hora.",
    "dst2025schedule.h1": "Calendario mundial del horario de verano 2025: Fechas completas de inicio y fin",
    "embedwidget.meta.title": "Widget de reloj mundial integrable gratuito | GlobeTimeZone",
    "embedwidget.meta.desc": "Añade un widget de reloj mundial gratuito a tu sitio web. Ciudades personalizables, tema claro/oscuro, compacto o completo. Copia el código en segundos.",
    "embedwidget.h1": "🆓 Widget de reloj mundial gratuito",
    "esttocstconverter.meta.title": "Convertidor EST a CST - Hora del Este a Hora Central | GlobeTimeZone",
    "esttocstconverter.meta.desc": "Convierte al instante EST (Hora Estándar del Este) a CST (Hora Estándar Central). Convertidor gratuito con tabla 24h y consejos de reuniones.",
    "esttocstconverter.h1": "🕐 Convertidor EST a CST",
    "esttopstconverter.meta.title": "Convertidor EST a PST - Hora del Este a Hora del Pacífico | GlobeTimeZone",
    "esttopstconverter.meta.desc": "Convierte al instante EST (Hora Estándar del Este) a PST (Hora Estándar del Pacífico). Convertidor gratuito con tabla 24h. Diferencia de 3 horas.",
    "esttopstconverter.h1": "🕐 Convertidor EST a PST",
    "europeaustraliatimedifference.meta.title": "Diferencia horaria Europa vs Australia (2026): Tabla 24h completa y mejores horas de reunión",
    "europeaustraliatimedifference.meta.desc": "Compara al instante las zonas horarias de Europa y Australia. Tabla de conversión completa, cambios de horario de verano en hemisferios opuestos, mejores ventanas y errores comunes.",
    "europeaustraliatimedifference.h1": "🦘 Convertidor de hora Europa a Australia",
    "gmttocstconverter.meta.title": "Convertidor GMT a CST - Greenwich a Hora Estándar de China | GlobeTimeZone",
    "gmttocstconverter.meta.desc": "Convierte al instante GMT (Hora Media de Greenwich) a CST (Hora Estándar de China). Convertidor gratuito con tabla 24h y visualización de horas de trabajo.",
    "gmttocstconverter.h1": "🕐 Convertidor GMT a CST",
    "hawaiitoest.meta.title": "Convertidor Hora de Hawái a EST (2026): Tabla completa y mejores horas de reunión US",
    "hawaiitoest.meta.desc": "Convierte rápidamente la hora de Hawái-Aleutianas a la hora del este de EE.UU. Tabla 24h, reglas de horario de verano 2026, mejores ventanas y errores comunes.",
    "hawaiitoest.h1": "🌺 Convertidor Hawái a EST",
    "holidays.meta.title": "Días festivos mundiales 2026 - Festivos públicos en 200+ países | GlobeTimeZone",
    "holidays.meta.desc": "Consulta los días festivos y observancias en 200+ países. Perfecto para la planificación comercial internacional, viajes y conciencia cultural.",
    "holidays.h1": "🎉 Días festivos mundiales 2026",
    "isttoestconverter.meta.title": "Convertidor IST a EST | India a Hora del Este | GlobeTimeZone",
    "isttoestconverter.meta.desc": "Convierte IST (Hora Estándar de India, UTC+5:30) a EST (Hora Estándar del Este, UTC-5). Convertidor interactivo, tabla 24h y mejores horas de reunión entre India y la costa este de EE.UU.",
    "isttoestconverter.h1": "Convertidor de hora IST a EST",
    "jsttocstconverter.meta.title": "Convertidor JST a CST - Japón a Hora Estándar de China | GlobeTimeZone",
    "jsttocstconverter.meta.desc": "Convierte al instante JST (Hora Estándar de Japón) a CST (Hora Estándar de China). Convertidor gratuito. Japón y China comparten el mismo offset UTC+8.",
    "jsttocstconverter.h1": "🕐 Convertidor JST a CST",
    "meetingscheduler.meta.title": "Planificador de reuniones - Encuentra las mejores horas entre zonas horarias | GlobeTimeZone",
    "meetingscheduler.meta.desc": "Planificador de reuniones inteligente gratuito. Encuentra las mejores horas de reunión en múltiples zonas horarias. Soporta planificación de equipos con visualización de horas de trabajo.",
    "meetingscheduler.h1": "📅 Planificador de reuniones",
    "privacypolicy.meta.title": "Política de privacidad - GlobeTimeZone",
    "privacypolicy.h1": "🔒 Política de privacidad",
    "privacy.meta.title": "Política de privacidad – GlobeTimeZone",
    "privacy.meta.desc": "Política de privacidad de GlobeTimeZone. No vendemos sus datos.",
    "privacy.h1": "Política de privacidad",
    "pro.meta.title": "GlobeTimeZone Pro - Funciones premium para usuarios avanzados",
    "pro.meta.desc": "Mejora a GlobeTimeZone Pro para relojes ilimitados, experiencia sin anuncios, acceso API y soporte prioritario.",
    "pro.h1": "🚀 GlobeTimeZone Pro",
    "psttocstconverter.meta.title": "Convertidor PST a CST | Pacífico a Hora Estándar de China | GlobeTimeZone",
    "psttocstconverter.meta.desc": "Convierte PST (Hora Estándar del Pacífico, UTC-8) a CST (Hora Estándar de China, UTC+8). Tabla 24h, convertidor rápido y mejores horas para llamadas entre California y China.",
    "psttocstconverter.h1": "Convertidor de hora PST a CST (China)",
    "psttoest.meta.title": "Convertidor PST a EST (2026): Tabla completa y mejores horas de reunión trans-US",
    "psttoest.meta.desc": "Convierte rápidamente la hora del Pacífico a la hora del Este. Tabla 24h, fechas de horario de verano 2026, mejores ventanas y errores de zonas horarias comunes.",
    "psttoest.h1": "🗼 Convertidor PST a EST",
    "remoteteamtimezoneguide.meta.title": "Guía de gestión de zonas horarias para equipos remotos | GlobeTimeZone",
    "remoteteamtimezoneguide.meta.desc": "Guía completa para gestionar equipos remotos a través de zonas horarias. Aprende a programar reuniones, mantener la productividad y construir cultura en equipos distribuidos.",
    "remoteteamtimezoneguide.h1": "🤝 Guía de gestión de zonas horarias para equipos remotos",
    "remoteteamtimezonetools.meta.title": "Comparativa de las mejores herramientas de zonas horarias para equipos remotos: Guía 2025 | GlobeTimeZone",
    "remoteteamtimezonetools.meta.desc": "Compara las mejores herramientas de zonas horarias para equipos remotos: Slack, Google Calendar, World Time Buddy, Clockwise y más. Elige la herramienta adecuada para tu equipo distribuido.",
    "remoteteamtimezonetools.h1": "Comparativa de las mejores herramientas de zonas horarias para equipos remotos: Guía completa 2025",
    "remoteworktimezone.meta.title": "Trabajo remoto y guía de zonas horarias para equipos globales | GlobeTimeZone",
    "remoteworktimezone.meta.desc": "Cómo gestionar las zonas horarias en un equipo remoto o distribuido. Mejores prácticas para programar reuniones, establecer horas centrales y evitar la fatiga de zonas horarias en equipos globales.",
    "remoteworktimezone.h1": "El manual completo de zonas horarias para equipos remotos",
    "subscribe.meta.title": "Suscríbete a GlobeTimeZone - Consejos y actualizaciones semanales de zonas horarias",
    "subscribe.meta.desc": "Suscríbete a GlobeTimeZone para consejos y actualizaciones de zonas horarias.",
    "subscribe.h1": "📬 Mantente sincronizado con GlobeTimeZone",
    "teamoverlap.meta.title": "Calculador de solapamiento horario de equipo - Encuentra horas de trabajo compartidas | GlobeTimeZone",
    "teamoverlap.meta.desc": "Encuentra horas de trabajo solapadas para tu equipo remoto a través de zonas horarias. Panel visual para ver cuándo todos están disponibles. Perfecto para equipos distribuidos.",
    "teamoverlap.h1": "👥 Calculador de solapamiento horario de equipo",
    "terms.meta.title": "Términos de servicio – GlobeTimeZone",
    "terms.meta.desc": "Términos de servicio de GlobeTimeZone. Nuestra herramienta es gratuita para uso personal y comercial.",
    "terms.h1": "Términos de servicio",
    "timedifference.chicagototokyo.meta.title": "Diferencia horaria entre Chicago y Tokio (2026)",
    "timedifference.chicagototokyo.meta.desc": "Chicago a Tokio: el corazón de América se encuentra con Japón a través de 14-15 horas. Comparación completa, mejores ventanas de llamada y experiencias prácticas.",
    "timedifference.chicagototokyo.h1": "Diferencia horaria entre Chicago y Tokio (2026): El corazón de América se encuentra con Japón",
    "timedifference.dubaitolosangeles.meta.title": "Diferencia horaria entre Dubái y Los Ángeles (2026): Guía completa",
    "timedifference.dubaitolosangeles.meta.desc": "Dubái a LA abarca 12-13 horas sin solapamiento de horario laboral. Guía completa de planificación con estrategias de flexibilidad asimétrica.",
    "timedifference.dubaitolosangeles.h1": "Diferencia horaria entre Dubái y Los Ángeles (2026): Del Golfo al Pacífico",
    "timedifference.frankfurttonewyork.meta.title": "Diferencia horaria entre Fráncfort y Nueva York (2026): Guía financiera",
    "timedifference.frankfurttonewyork.meta.desc": "Fráncfort y Nueva York impulsan los mercados financieros mundiales. Comparación completa, ventanas de trading y experiencias prácticas.",
    "timedifference.frankfurttonewyork.h1": "Diferencia horaria entre Fráncfort y Nueva York (2026): Las finanzas europeas se encuentran con los mercados americanos",
    "timedifference.hongkongtolosangeles.meta.title": "Diferencia horaria entre Hong Kong y Los Ángeles (2026): Guía completa",
    "timedifference.hongkongtolosangeles.meta.desc": "Hong Kong a LA cruza el Pacífico con 15-16 horas de diferencia. Guía completa, mejores ventanas y experiencias prácticas.",
    "timedifference.hongkongtolosangeles.h1": "Diferencia horaria entre Hong Kong y Los Ángeles (2026): El corazón financiero de Asia se encuentra con Hollywood",
    "timedifference.latobeijing.meta.title": "Diferencia horaria entre Los Ángeles y Pekín (2026): Trabajo transpacífico",
    "timedifference.latobeijing.meta.desc": "¿Planificando llamadas entre LA y Pekín? La brecha de 15-16 horas significa que alguien siempre trabaja fuera del horario 9-5. Estrategias de planificación completas.",
    "timedifference.latobeijing.h1": "Diferencia horaria entre Los Ángeles y Pekín (2026): Trabajo transpacífico",
    "timedifference.miamitolondon.meta.title": "Diferencia horaria entre Miami y Londres (2026)",
    "timedifference.miamitolondon.meta.desc": "Miami a Londres: el sol se encuentra con la niebla a través de 5-7 horas. Comparación completa, mejores ventanas y experiencias prácticas.",
    "timedifference.miamitolondon.h1": "Diferencia horaria entre Miami y Londres (2026): El sol se encuentra con la niebla",
    "timedifference.mumbaitodubai.meta.title": "Diferencia horaria entre Mumbai y Dubái (2026)",
    "timedifference.mumbaitodubai.meta.desc": "Mumbai a Dubái: el sur de Asia se encuentra con el Golfo a través de solo 1,5 horas. Comparación completa y mejores ventanas de llamada.",
    "timedifference.mumbaitodubai.h1": "Diferencia horaria entre Mumbai y Dubái (2026): Vecinos cercanos",
    "timedifference.newyorktolondon.meta.title": "Diferencia horaria entre Nueva York y Londres (2026): Guía completa de finanzas, tecnología y negocios",
    "timedifference.newyorktolondon.meta.desc": "Diferencia horaria Nueva York-Londres explicada: 4-5 horas según el horario de verano. Ventanas financieras/de trading, tips de reuniones tech, fechas de horario de verano 2026 y convertidor gratuito. Guía experta.",
    "timedifference.newyorktolondon.h1": "Diferencia horaria entre Nueva York y Londres (2026): La guía completa de negocios y finanzas",
    "timedifference.nuevayorkalondres.meta.title": "Diferencia horaria entre Nueva York y Londres (2026): Convertidor y mejores horarios de reunión",
    "timedifference.nuevayorkalondres.meta.desc": "Convierte instantáneamente la hora entre Nueva York y Londres con nuestra herramienta gratuita. Reglas de horario de verano 2026, mejores horarios de reunión y errores comunes.",
    "timedifference.nuevayorkalondres.h1": "Diferencia horaria entre Nueva York y Londres (2026): Convertidor completo y mejores horarios",
    "timedifference.paristonewyork.meta.title": "Diferencia horaria entre París y Nueva York (2026): Guía completa",
    "timedifference.paristonewyork.meta.desc": "París-Nueva York es una de las rutas transatlánticas más fáciles — hasta que el horario de verano te sorprende. Comparación completa y errores comunes.",
    "timedifference.paristonewyork.h1": "Diferencia horaria entre París y Nueva York (2026): La ruta casi fácil",
    "timedifference.seoultolondon.meta.title": "Diferencia horaria entre Seúl y Londres (2026)",
    "timedifference.seoultolondon.meta.desc": "Seúl a Londres: la cultura K se encuentra con la tradición británica a través de 8-9 horas. Comparación completa, mejores ventanas y experiencias prácticas.",
    "timedifference.seoultolondon.h1": "Diferencia horaria entre Seúl y Londres (2026): La capital de la cultura K se encuentra con Gran Bretaña",
    "timedifference.singaporetolondon.meta.title": "Diferencia horaria entre Singapur y Londres (2026)",
    "timedifference.singaporetolondon.meta.desc": "Singapur a Londres abarca 7-8 horas entre continentes. Experiencias prácticas para gestionar llamadas entre la Ciudad del León y la City de Londres, incluyendo tips de finanzas y trading.",
    "timedifference.singaporetolondon.h1": "Diferencia horaria entre Singapur y Londres (2026): La guía de negocios completa",
    "timedifference.sydneytolondon.meta.title": "Diferencia horaria entre Sídney y Londres (2026): Guía completa",
    "timedifference.sydneytolondon.meta.desc": "Sídney a Londres cubre casi 17.000 km con solapamientos complejos de horario de verano. Años de experiencia en esta ruta, incluyendo estrategias de planificación.",
    "timedifference.sydneytolondon.h1": "Diferencia horaria entre Sídney y Londres (2026): Navegando hemisferios opuestos",
    "timedifference.sydneytonewyork.meta.title": "Diferencia horaria entre Sídney y Nueva York (2026)",
    "timedifference.sydneytonewyork.meta.desc": "Sídney a Nueva York: hemisferios opuestos, brecha de 14-19 horas. Comparación completa, mejores ventanas y experiencias prácticas.",
    "timedifference.sydneytonewyork.h1": "Diferencia horaria entre Sídney y Nueva York (2026): Hemisferios opuestos",
    "timedifference.tokyotonewyork.meta.title": "Diferencia horaria entre Tokio y Nueva York (2026): La guía definitiva de negocios y viajes",
    "timedifference.tokyotonewyork.meta.desc": "Guía completa Tokio-Nueva York: diferencia de 13-14 horas explicada. Planificador de reuniones, fechas de horario de verano 2026, tips por sector finanzas, tecnología y entretenimiento. Convertidor gratuito incluido.",
    "timedifference.tokyotonewyork.h1": "Diferencia horaria entre Tokio y Nueva York (2026): La guía completa de negocios y viajes",
    "timedifference.torontotoshanghai.meta.title": "Diferencia horaria entre Toronto y Shanghái (2026): Guía completa",
    "timedifference.torontotoshanghai.meta.desc": "Toronto-Shanghái no tiene solapamiento de horario laboral — la brecha de 12-13 horas significa que alguien siempre debe estar en línea fuera de horario. Estrategias de planificación completas.",
    "timedifference.torontotoshanghai.h1": "Diferencia horaria entre Toronto y Shanghái (2026): Gestionando la ruta sin solapamiento",
    "timedifference.洛杉矶到北京.meta.title": "Diferencia horaria entre Los Ángeles y Pekín (2026): Tabla completa y mejores horas de llamada",
    "timedifference.洛杉矶到北京.meta.desc": "Consulta la diferencia horaria exacta entre LA y Pekín, tabla de conversión 24h, reglas de horario de verano 2026 y mejores horas para llamadas de negocios transpacíficas.",
    "timedifference.洛杉矶到北京.h1": "Diferencia horaria entre Los Ángeles y Pekín (2026): Tabla completa y mejores horas de llamada",
    "timein.beijing.meta.title": "Hora actual en Pekín | Zona horaria, fecha | GlobeTimeZone",
    "timein.beijing.meta.desc": "Consulta la hora actual en Pekín, China. Hora exacta, fecha, diferencia de zona horaria (CST, UTC+8). Sin horario de verano. Compara con otras ciudades del mundo.",
    "timein.beijing.h1": "Hora actual en Pekín",
    "timein.chicago.meta.title": "Hora actual en Chicago | Zona CST/CDT | GlobeTimeZone",
    "timein.chicago.meta.desc": "Consulta la hora actual en Chicago, Illinois. Reloj en vivo, CST/CDT hora central (UTC-6/UTC-5), estado del horario de verano y comparación con las principales ciudades del mundo.",
    "timein.chicago.h1": "Hora actual en Chicago",
    "timein.dubai.meta.title": "Hora actual en Dubái | GST (UTC+4) | GlobeTimeZone",
    "timein.dubai.meta.desc": "Consulta la hora actual en Dubái, EAU. Reloj en vivo, zona GST (UTC+4), sin horario de verano. Compara la hora de Dubái con otras ciudades.",
    "timein.dubai.h1": "Hora actual en Dubái",
    "timein.london.meta.title": "Hora actual en Londres | Zona horaria, fecha | GlobeTimeZone",
    "timein.london.meta.desc": "Consulta la hora actual en Londres, Reino Unido. Hora exacta, fecha, diferencia de zona horaria (GMT/BST), horas de amanecer y atardecer. Compara con otras ciudades del mundo.",
    "timein.london.h1": "Hora actual en Londres",
    "timein.losangeles.meta.title": "Hora actual en Los Ángeles | PST/PDT | GlobeTimeZone",
    "timein.losangeles.meta.desc": "Consulta la hora actual en Los Ángeles, California. Reloj en vivo, PST/PDT hora del Pacífico (UTC-8/UTC-7), estado del horario de verano y comparación mundial.",
    "timein.losangeles.h1": "Hora actual en Los Ángeles",
    "timein.newyork.meta.title": "Hora actual en Nueva York | Zona horaria, fecha | GlobeTimeZone",
    "timein.newyork.meta.desc": "Consulta la hora actual en Nueva York, EE.UU. Hora exacta, fecha, diferencia de zona horaria (EST/EDT). Compara con otras ciudades del mundo.",
    "timein.newyork.h1": "Hora actual en Nueva York",
    "timein.paris.meta.title": "Hora actual en París | CET/CEST | GlobeTimeZone",
    "timein.paris.meta.desc": "Consulta la hora actual en París, Francia. Reloj en vivo, fecha, diferencia CET/CEST, estado del horario de verano. Compara la hora de París con otras ciudades.",
    "timein.paris.h1": "Hora actual en París",
    "timein.seoul.meta.title": "Hora actual en Seúl | KST (UTC+9) | GlobeTimeZone",
    "timein.seoul.meta.desc": "Consulta la hora actual en Seúl, Corea del Sur. Reloj en vivo, zona KST (UTC+9), sin horario de verano y comparación con Pekín, Tokio y Nueva York.",
    "timein.seoul.h1": "Hora actual en Seúl",
    "timein.singapore.meta.title": "Hora actual en Singapur | SGT (UTC+8) | GlobeTimeZone",
    "timein.singapore.meta.desc": "Consulta la hora actual en Singapur. Reloj en vivo, zona SGT (UTC+8), sin horario de verano. Compara con Londres, Nueva York, Pekín y más.",
    "timein.singapore.h1": "Hora actual en Singapur",
    "timein.sydney.meta.title": "Hora actual en Sídney | AEDT/AEST | GlobeTimeZone",
    "timein.sydney.meta.desc": "Consulta la hora actual en Sídney, Australia. Reloj en vivo, AEDT/AEST (UTC+11/UTC+10), estado del horario de verano y comparación mundial.",
    "timein.sydney.h1": "Hora actual en Sídney",
    "timein.tokyo.meta.title": "Hora actual en Tokio | Zona horaria, fecha | GlobeTimeZone",
    "timein.tokyo.meta.desc": "Consulta la hora actual en Tokio, Japón. Hora exacta, fecha, diferencia de zona horaria (JST, UTC+9). Sin horario de verano. Compara con otras ciudades del mundo.",
    "timein.tokyo.h1": "Hora actual en Tokio",
    "timein.toronto.meta.title": "Hora actual en Toronto | EST/EDT | GlobeTimeZone",
    "timein.toronto.meta.desc": "Consulta la hora actual en Toronto, Canadá. Reloj en vivo, EST/EDT hora del Este (UTC-5/UTC-4), estado del horario de verano y comparación mundial.",
    "timein.toronto.h1": "Hora actual en Toronto",
    "timeunits.meta.title": "Convertidor de unidades de tiempo - Horas, minutos, segundos, tiempo decimal | GlobeTimeZone",
    "timeunits.meta.desc": "Convertidor de unidades de tiempo gratuito. Convierte entre horas, minutos, segundos, horas decimales y más. Perfecto para nóminas, gestión de proyectos y seguimiento de tiempo.",
    "timeunits.h1": "🔄 Convertidor de unidades de tiempo",
    "timestampevidence.meta.title": "GlobeTimeZone - Paquete de prueba de marca de tiempo digital",
    "timestampevidence.meta.desc": "Paquete de prueba de marca de tiempo digital de alta fiabilidad - Conforme con la Ley de Firmas Electrónicas",
    "timestampevidence.h1": "Certificado de marca de tiempo digital de alta fiabilidad GlobeTimeZone",
    "timezoneguide.meta.title": "Guía completa de zonas horarias mundiales | GlobeTimeZone",
    "timezoneguide.meta.desc": "Todo lo que necesitas saber sobre las zonas horarias mundiales: offsets UTC, cómo funcionan, la base de datos IANA, UTC vs GMT y consejos para planificar entre zonas horarias.",
    "timezoneguide.h1": "Guía completa de zonas horarias mundiales",
    "timezonehistory.meta.title": "Historia fascinante de las zonas horarias: La línea internacional de cambio de fecha, el día perdido de Samoa y más | GlobeTimeZone",
    "timezonehistory.meta.desc": "Descubre las historias más fascinantes de la historia de las zonas horarias: cómo se creó la línea internacional de cambio de fecha, por qué Samoa saltó un día, el caos del tiempo ferroviario y la política del UTC.",
    "timezonehistory.h1": "Historia fascinante de las zonas horarias: La línea de fecha, días perdidos y el caos ferroviario",
    "uschinatimedifference.meta.title": "Diferencia horaria EE.UU. vs China – GlobeTimeZone.com",
    "uschinatimedifference.meta.desc": "¿Cuál es la diferencia horaria entre EE.UU. y China? Guía completa de zonas horarias EE.UU.-China, horario de verano y mejores horas para llamadas.",
    "uschinatimedifference.h1": "Diferencia horaria EE.UU. vs China: Guía completa (2026)",
    "utc8toutc5.meta.title": "Convertidor UTC+8 a UTC-5 (2026): Tabla 24h completa y horas de reunión globales",
    "utc8toutc5.meta.desc": "Convierte al instante UTC+8 (China) a UTC-5 (Este de EE.UU.). Tabla 24h, cambios de horario de verano 2026, mejores ventanas y errores comunes.",
    "utc8toutc5.h1": "🌏 Convertidor UTC+8 a UTC-5",
    "utctocstconverter.meta.title": "Convertidor UTC a CST - Tiempo Universal a Hora Estándar de China | GlobeTimeZone",
    "utctocstconverter.meta.desc": "Convierte al instante UTC a CST (Hora Estándar de China). Convertidor UTC-Pekín/Shanghái con tabla 24h e información de horario de verano.",
    "utctocstconverter.h1": "🕐 Convertidor UTC a CST",
    "whydaylightsavingtime.meta.title": "¿Por qué existe el horario de verano? Guía completa | GlobeTimeZone",
    "whydaylightsavingtime.meta.desc": "Descubre la historia y las razones del horario de verano. ¿Por qué cambiamos la hora dos veces al año? ¿Qué países todavía usan el horario de verano? Lee nuestra guía completa.",
    "whydaylightsavingtime.h1": "¿Por qué existe el horario de verano?",
    "worldclock.meta.title": "Reloj mundial - Hora en vivo en todas las principales ciudades | GlobeTimeZone",
    "worldclock.meta.desc": "Reloj mundial en vivo mostrando la hora actual en todas las principales ciudades del mundo. Actualizaciones automáticas del horario de verano. Compara Nueva York, Londres, Tokio, Sídney y más.",
    "worldclock.h1": "🌐 Reloj mundial",
    "worldmap.meta.title": "Mapa interactivo de zonas horarias mundiales | GlobeTimeZone",
    "worldmap.meta.desc": "Mapa interactivo de zonas horarias mundiales. Haz clic en las regiones para comparar horas en todo el mundo. Perfecto para entender las diferencias horarias globales.",
    "worldmap.h1": "🗺️ Mapa de zonas horarias mundiales",
}

# (ja, ko, pt, ar continue below — they'll be written as separate file writes)
# This script is split for clarity; the main generation writes all 7 files.

LANGS = {
    "de": de,
    "fr": fr,
    "es": es,
}

def write_json(lang_code, data):
    # Verify all keys present
    missing = [k for k in KEYS_ORDER if k not in data]
    extra = [k for k in data if k not in KEYS_ORDER]
    if missing:
        print(f"  ⚠️  {lang_code}: missing {len(missing)} keys: {missing[:5]}...")
    if extra:
        print(f"  ⚠️  {lang_code}: extra {len(extra)} keys: {extra[:5]}...")
    
    path = os.path.join(LOCALES_DIR, f"{lang_code}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"  ✅ {lang_code}.json — {len(data)} keys written to {path}")

if __name__ == "__main__":
    print("Generating language JSON files (batch 1: de/fr/es)...")
    for code, data in LANGS.items():
        write_json(code, data)
