"""
inject_xb_keys.py
Injects all xb.* i18n keys into the 9 locale JSON files.
"""
import json, os

locales_dir = r'C:/Users/ASUS/WorkBuddy/Claw/globetimezone/locales'

xb_keys = {
  # carriers
  'xb.carrier.dhl': {'zh':'DHL 国际快递','en':'DHL International Express','de':'DHL International Express','fr':'DHL Express International','es':'DHL Express Internacional','ja':'DHL国際宅配便','ko':'DHL 국제 특급','pt':'DHL Express Internacional','ar':'DHL إكسبريس الدولي'},
  'xb.carrier.ups': {'zh':'UPS 国际快递','en':'UPS International Express','de':'UPS International Express','fr':'UPS Express International','es':'UPS Express Internacional','ja':'UPS国際宅配便','ko':'UPS 국제 특급','pt':'UPS Express Internacional','ar':'UPS إكسبريس الدولي'},
  'xb.carrier.fedex': {'zh':'FedEx 联邦快递','en':'FedEx International','de':'FedEx International','fr':'FedEx International','es':'FedEx Internacional','ja':'FedEx国際宅配便','ko':'FedEx 국제','pt':'FedEx Internacional','ar':'فيديكس الدولي'},
  'xb.carrier.tnt': {'zh':'TNT 国际快递','en':'TNT International Express','de':'TNT International Express','fr':'TNT Express International','es':'TNT Express Internacional','ja':'TNT国際宅配便','ko':'TNT 국제 특급','pt':'TNT Express Internacional','ar':'TNT إكسبريس الدولي'},
  'xb.carrier.ems': {'zh':'EMS 国际特快','en':'EMS International Express','de':'EMS Internationaler Expressversand','fr':'EMS Express International','es':'EMS Express Internacional','ja':'EMS国際スピード郵便','ko':'EMS 국제 특급 우편','pt':'EMS Express Internacional','ar':'EMS بريد دولي سريع'},
  'xb.carrier.fba.name': {'zh':'亚马逊FBA','en':'Amazon FBA','de':'Amazon FBA','fr':'Amazon FBA','es':'Amazon FBA','ja':'アマゾンFBA','ko':'아마존 FBA','pt':'Amazon FBA','ar':'أمازون FBA'},
  'xb.carrier.fba': {'zh':'亚马逊 FBA 专线','en':'Amazon FBA Direct Line','de':'Amazon FBA Direktlinie','fr':'Amazon FBA Ligne Directe','es':'Amazon FBA Línea Directa','ja':'アマゾンFBA専用ライン','ko':'아마존 FBA 전용 라인','pt':'Amazon FBA Linha Direta','ar':'أمازون FBA خط مباشر'},
  'xb.carrier.air.name': {'zh':'空运专线','en':'Air Freight','de':'Luftfracht','fr':'Fret Aérien','es':'Carga Aérea','ja':'航空便専用ライン','ko':'항공 전용 라인','pt':'Frete Aéreo','ar':'شحن جوي'},
  'xb.carrier.air': {'zh':'空运专线','en':'Air Freight Line','de':'Luftfrachtlinie','fr':'Ligne Fret Aérien','es':'Línea de Carga Aérea','ja':'航空便専用ライン','ko':'항공 전용 라인','pt':'Linha de Frete Aéreo','ar':'خط الشحن الجوي'},
  'xb.carrier.sea.name': {'zh':'海运快船','en':'Sea Freight','de':'Seefracht','fr':'Fret Maritime','es':'Carga Marítima','ja':'海上輸送快速便','ko':'해운 쾌속선','pt':'Frete Marítimo','ar':'شحن بحري'},
  'xb.carrier.sea': {'zh':'海运快船','en':'Sea Freight Express','de':'Seefracht Express','fr':'Fret Maritime Express','es':'Carga Marítima Rápida','ja':'海上輸送快速便','ko':'해운 쾌속선','pt':'Frete Marítimo Expresso','ar':'شحن بحري سريع'},
  # features
  'xb.feat.fastest': {'zh':'最快时效','en':'Fastest delivery','de':'Schnellste Lieferung','fr':'Livraison la plus rapide','es':'Entrega más rápida','ja':'最速配達','ko':'최단 배송','pt':'Entrega mais rápida','ar':'أسرع تسليم'},
  'xb.feat.tracking': {'zh':'全程追踪','en':'Full tracking','de':'Vollständige Nachverfolgung','fr':'Suivi complet','es':'Seguimiento completo','ja':'全行程追跡','ko':'전체 추적','pt':'Rastreamento completo','ar':'تتبع كامل'},
  'xb.feat.priority': {'zh':'优先清关','en':'Priority customs clearance','de':'Vorrangige Zollabfertigung','fr':'Dédouanement prioritaire','es':'Despacho aduanero prioritario','ja':'優先通関','ko':'우선 통관','pt':'Desembaraço aduaneiro prioritário','ar':'تخليص جمركي ذو أولوية'},
  'xb.feat.reliable': {'zh':'稳定可靠','en':'Reliable & stable','de':'Zuverlässig & stabil','fr':'Fiable et stable','es':'Confiable y estable','ja':'安定信頼性','ko':'안정적 신뢰','pt':'Confiável e estável','ar':'موثوق ومستقر'},
  'xb.feat.na': {'zh':'北美优势','en':'North America advantage','de':'Nordamerika-Vorteil','fr':'Avantage Amérique du Nord','es':'Ventaja en América del Norte','ja':'北米優位','ko':'북미 강점','pt':'Vantagem na América do Norte','ar':'ميزة أمريكا الشمالية'},
  'xb.feat.pickup': {'zh':'上门取件','en':'Door pickup','de':'Abholung vor Ort','fr':'Collecte à domicile','es':'Recogida a domicilio','ja':'ドア集荷','ko':'방문 픽업','pt':'Coleta domiciliar','ar':'استلام من الباب'},
  'xb.feat.global': {'zh':'全球覆盖','en':'Global coverage','de':'Weltweite Abdeckung','fr':'Couverture mondiale','es':'Cobertura global','ja':'グローバルカバー','ko':'글로벌 커버리지','pt':'Cobertura global','ar':'تغطية عالمية'},
  'xb.feat.economical': {'zh':'经济实惠','en':'Cost-effective','de':'Kostengünstig','fr':'Économique','es':'Económico','ja':'コスト効率が良い','ko':'경제적','pt':'Econômico','ar':'اقتصادي'},
  'xb.feat.ontime': {'zh':'准时率高','en':'High on-time rate','de':'Hohe Pünktlichkeitsrate','fr':'Taux de ponctualité élevé','es':'Alta tasa de puntualidad','ja':'高い定時率','ko':'높은 정시 배송률','pt':'Alta taxa de pontualidade','ar':'معدل التسليم في الوقت المحدد مرتفع'},
  'xb.feat.europe': {'zh':'欧洲优势','en':'Europe advantage','de':'Europa-Vorteil','fr':'Avantage Europe','es':'Ventaja en Europa','ja':'欧州優位','ko':'유럽 강점','pt':'Vantagem na Europa','ar':'ميزة أوروبا'},
  'xb.feat.customs': {'zh':'清关能力强','en':'Strong customs clearance','de':'Starke Zollabfertigung','fr':'Dédouanement puissant','es':'Fuerte capacidad aduanera','ja':'強力な通関能力','ko':'강력한 통관 역량','pt':'Forte capacidade alfandegária','ar':'قدرة جمركية قوية'},
  'xb.feat.midprice': {'zh':'价格适中','en':'Mid-range price','de':'Mittlerer Preisbereich','fr':'Prix intermédiaire','es':'Precio intermedio','ja':'中価格帯','ko':'중간 가격','pt':'Preço intermediário','ar':'سعر متوسط'},
  'xb.feat.novol': {'zh':'不计体积重','en':'No volumetric weight','de':'Kein Volumengewicht','fr':'Pas de poids volumétrique','es':'Sin peso volumétrico','ja':'容積重量なし','ko':'체적 중량 없음','pt':'Sem peso volumétrico','ar':'لا وزن حجمي'},
  'xb.feat.postal': {'zh':'邮政渠道','en':'Postal channel','de':'Postkanal','fr':'Canal postal','es':'Canal postal','ja':'郵政ルート','ko':'우편 채널','pt':'Canal postal','ar':'قناة بريدية'},
  'xb.feat.fba': {'zh':'FBA入仓','en':'FBA warehouse','de':'FBA-Lager','fr':'Entrepôt FBA','es':'Almacén FBA','ja':'FBA倉庫','ko':'FBA 입고','pt':'Armazém FBA','ar':'مستودع FBA'},
  'xb.feat.ddp': {'zh':'双清包税','en':'DDP (tax included)','de':'DDP (inkl. Zoll)','fr':'DDP (taxes incluses)','es':'DDP (impuestos incluidos)','ja':'DDP（関税込み）','ko':'DDP (세금 포함)','pt':'DDP (impostos incluídos)','ar':'DDP (شامل الضرائب)'},
  'xb.feat.cheap': {'zh':'价格优惠','en':'Affordable price','de':'Günstiger Preis','fr':'Prix abordable','es':'Precio asequible','ja':'お手頃価格','ko':'저렴한 가격','pt':'Preço acessível','ar':'سعر معقول'},
  'xb.feat.costeffective': {'zh':'性价比高','en':'High value for money','de':'Gutes Preis-Leistungs-Verhältnis','fr':'Excellent rapport qualité-prix','es':'Alta relación calidad-precio','ja':'コストパフォーマンス高い','ko':'비용 대비 높은 가치','pt':'Ótimo custo-benefício','ar':'قيمة مقابل المال عالية'},
  'xb.feat.bulk': {'zh':'大货优势','en':'Bulk cargo advantage','de':'Vorteil für Großfracht','fr':'Avantage pour les gros volumes','es':'Ventaja para carga masiva','ja':'大量貨物優位','ko':'대량 화물 강점','pt':'Vantagem para carga em volume','ar':'ميزة البضائع الضخمة'},
  'xb.feat.oversize': {'zh':'超大货优势','en':'Oversize cargo advantage','de':'Vorteil für Übergröße','fr':'Avantage pour cargaison surdimensionnée','es':'Ventaja para carga sobredimensionada','ja':'大型貨物優位','ko':'초대형 화물 강점','pt':'Vantagem para carga de grande porte','ar':'ميزة البضائع الكبيرة الحجم'},
  'xb.feat.lowest': {'zh':'成本最低','en':'Lowest cost','de':'Niedrigste Kosten','fr':'Coût le plus bas','es':'Menor costo','ja':'最低コスト','ko':'최저 비용','pt':'Menor custo','ar':'أدنى تكلفة'},
  # destinations
  'xb.dest.useast': {'zh':'美国东部·纽约','en':'US East · New York','de':'USA Ostküste · New York','fr':'USA Est · New York','es':'EE.UU. Este · Nueva York','ja':'米国東部・ニューヨーク','ko':'미국 동부·뉴욕','pt':'EUA Leste · Nova York','ar':'الولايات المتحدة الشرقية · نيويورك'},
  'xb.dest.uswest': {'zh':'美国西部·洛杉矶','en':'US West · Los Angeles','de':'USA Westküste · Los Angeles','fr':'USA Ouest · Los Angeles','es':'EE.UU. Oeste · Los Ángeles','ja':'米国西部・ロサンゼルス','ko':'미국 서부·로스앤젤레스','pt':'EUA Oeste · Los Angeles','ar':'الولايات المتحدة الغربية · لوس أنجلوس'},
  'xb.dest.uk': {'zh':'英国·伦敦','en':'UK · London','de':'Großbritannien · London','fr':'Royaume-Uni · Londres','es':'Reino Unido · Londres','ja':'英国・ロンドン','ko':'영국·런던','pt':'Reino Unido · Londres','ar':'المملكة المتحدة · لندن'},
  'xb.dest.de': {'zh':'德国·柏林','en':'Germany · Berlin','de':'Deutschland · Berlin','fr':'Allemagne · Berlin','es':'Alemania · Berlín','ja':'ドイツ・ベルリン','ko':'독일·베를린','pt':'Alemanha · Berlim','ar':'ألمانيا · برلين'},
  'xb.dest.fr': {'zh':'法国·巴黎','en':'France · Paris','de':'Frankreich · Paris','fr':'France · Paris','es':'Francia · París','ja':'フランス・パリ','ko':'프랑스·파리','pt':'França · Paris','ar':'فرنسا · باريس'},
  'xb.dest.jp': {'zh':'日本·东京','en':'Japan · Tokyo','de':'Japan · Tokio','fr':'Japon · Tokyo','es':'Japón · Tokio','ja':'日本・東京','ko':'일본·도쿄','pt':'Japão · Tóquio','ar':'اليابان · طوكيو'},
  'xb.dest.au': {'zh':'澳大利亚·悉尼','en':'Australia · Sydney','de':'Australien · Sydney','fr':'Australie · Sydney','es':'Australia · Sídney','ja':'オーストラリア・シドニー','ko':'호주·시드니','pt':'Austrália · Sydney','ar':'أستراليا · سيدني'},
  'xb.dest.ca': {'zh':'加拿大·多伦多','en':'Canada · Toronto','de':'Kanada · Toronto','fr':'Canada · Toronto','es':'Canadá · Toronto','ja':'カナダ・トロント','ko':'캐나다·토론토','pt':'Canadá · Toronto','ar':'كندا · تورونتو'},
  # origins
  'xb.origin.shenzhen': {'zh':'深圳','en':'Shenzhen','de':'Shenzhen','fr':'Shenzhen','es':'Shenzhen','ja':'深圳','ko':'선전','pt':'Shenzhen','ar':'شنتشن'},
  'xb.origin.guangzhou': {'zh':'广州','en':'Guangzhou','de':'Guangzhou','fr':'Guangzhou','es':'Guangzhou','ja':'広州','ko':'광저우','pt':'Guangzhou','ar':'قوانغتشو'},
  'xb.origin.yiwu': {'zh':'义乌','en':'Yiwu','de':'Yiwu','fr':'Yiwu','es':'Yiwu','ja':'義烏','ko':'이우','pt':'Yiwu','ar':'ييوو'},
  'xb.origin.shanghai': {'zh':'上海','en':'Shanghai','de':'Shanghai','fr':'Shanghai','es':'Shanghái','ja':'上海','ko':'상하이','pt':'Shanghai','ar':'شنغهاي'},
  'xb.origin.ningbo': {'zh':'宁波','en':'Ningbo','de':'Ningbo','fr':'Ningbo','es':'Ningbo','ja':'寧波','ko':'닝보','pt':'Ningbo','ar':'نينغبو'},
  'xb.origin.qingdao': {'zh':'青岛','en':'Qingdao','de':'Qingdao','fr':'Qingdao','es':'Qingdao','ja':'青島','ko':'칭다오','pt':'Qingdao','ar':'تشينغداو'},
  # HS codes
  'xb.hs.laptop': {'zh':'笔记本电脑','en':'Laptop computer','de':'Laptop-Computer','fr':'Ordinateur portable','es':'Computadora portátil','ja':'ノートパソコン','ko':'노트북 컴퓨터','pt':'Computador portátil','ar':'حاسوب محمول'},
  'xb.hs.phone': {'zh':'智能手机','en':'Smartphone','de':'Smartphone','fr':'Smartphone','es':'Teléfono inteligente','ja':'スマートフォン','ko':'스마트폰','pt':'Smartphone','ar':'هاتف ذكي'},
  'xb.hs.earphone': {'zh':'耳机/耳塞','en':'Earphones/earbuds','de':'Kopfhörer/Ohrstöpsel','fr':'Écouteurs/oreillettes','es':'Auriculares/tapones','ja':'イヤホン/耳栓','ko':'이어폰/이어버드','pt':'Fones de ouvido','ar':'سماعات أذن'},
  'xb.hs.toy': {'zh':'玩具/模型','en':'Toys/models','de':'Spielzeug/Modelle','fr':'Jouets/maquettes','es':'Juguetes/maquetas','ja':'おもちゃ/模型','ko':'장난감/모델','pt':'Brinquedos/modelos','ar':'ألعاب/نماذج'},
  'xb.hs.tshirt': {'zh':'T恤/上衣','en':'T-shirt/top','de':'T-Shirt/Oberteil','fr':'T-shirt/haut','es':'Camiseta/top','ja':'Tシャツ/トップス','ko':'티셔츠/상의','pt':'Camiseta/blusa','ar':'تيشيرت/قميص علوي'},
  'xb.hs.pants': {'zh':'裤子/牛仔裤','en':'Trousers/jeans','de':'Hosen/Jeans','fr':'Pantalons/jeans','es':'Pantalones/vaqueros','ja':'ズボン/ジーンズ','ko':'바지/청바지','pt':'Calças/jeans','ar':'بنطلون/جينز'},
  'xb.hs.shoes': {'zh':'运动鞋','en':'Sports shoes','de':'Sportschuhe','fr':'Chaussures de sport','es':'Zapatillas deportivas','ja':'スポーツシューズ','ko':'운동화','pt':'Tênis esportivo','ar':'أحذية رياضية'},
  'xb.hs.bag': {'zh':'手提包/箱包','en':'Handbag/luggage','de':'Handtasche/Gepäck','fr':'Sac à main/bagages','es':'Bolso/equipaje','ja':'ハンドバッグ/スーツケース','ko':'핸드백/가방','pt':'Bolsa/bagagem','ar':'حقيبة يد/أمتعة'},
  'xb.hs.skincare': {'zh':'护肤品/面霜','en':'Skincare/face cream','de':'Hautpflege/Gesichtscreme','fr':'Soin de la peau/crème','es':'Cuidado de la piel/crema','ja':'スキンケア/フェイスクリーム','ko':'스킨케어/크림','pt':'Skincare/creme facial','ar':'العناية بالبشرة/كريم الوجه'},
  'xb.hs.makeup': {'zh':'眼妆/睫毛膏','en':'Eye makeup/mascara','de':'Augen-Make-up/Mascara','fr':'Maquillage yeux/mascara','es':'Maquillaje de ojos/rímel','ja':'アイメイク/マスカラ','ko':'아이 메이크업/마스카라','pt':'Maquiagem de olhos/rímel','ar':'مكياج العيون/ماسكارا'},
  'xb.hs.jewelry': {'zh':'时尚饰品','en':'Fashion jewelry','de':'Modeschmuck','fr':'Bijoux de mode','es':'Joyería de moda','ja':'ファッションジュエリー','ko':'패션 주얼리','pt':'Joias de moda','ar':'مجوهرات أزياء'},
  'xb.hs.fitness': {'zh':'健身器材','en':'Fitness equipment','de':'Fitnessgeräte','fr':'Équipement de fitness','es':'Equipos de fitness','ja':'フィットネス機器','ko':'피트니스 기구','pt':'Equipamento de fitness','ar':'معدات اللياقة البدنية'},
  'xb.hs.furniture': {'zh':'家具/家居','en':'Furniture/home goods','de':'Möbel/Haushaltswaren','fr':'Meubles/articles ménagers','es':'Muebles/artículos del hogar','ja':'家具/インテリア','ko':'가구/홈 용품','pt':'Móveis/artigos domésticos','ar':'أثاث/سلع منزلية'},
  'xb.hs.camera': {'zh':'相机/摄像机','en':'Camera/camcorder','de':'Kamera/Camcorder','fr':'Appareil photo/caméscope','es':'Cámara/videocámara','ja':'カメラ/ビデオカメラ','ko':'카메라/캠코더','pt':'Câmera/filmadora','ar':'كاميرا/كاميرا فيديو'},
  'xb.hs.keyboard': {'zh':'键盘鼠标','en':'Keyboard & mouse','de':'Tastatur & Maus','fr':'Clavier et souris','es':'Teclado y ratón','ja':'キーボード/マウス','ko':'키보드 & 마우스','pt':'Teclado e mouse','ar':'لوحة المفاتيح والفأرة'},
  'xb.hs.cable': {'zh':'数据线/充电线','en':'Data cable/charging cable','de':'Datenkabel/Ladekabel','fr':'Câble de données/charge','es':'Cable de datos/carga','ja':'データケーブル/充電ケーブル','ko':'데이터 케이블/충전 케이블','pt':'Cabo de dados/carregamento','ar':'كابل بيانات/شحن'},
  'xb.hs.charger': {'zh':'充电器/电源适配器','en':'Charger/power adapter','de':'Ladegerät/Netzteil','fr':'Chargeur/adaptateur secteur','es':'Cargador/adaptador de corriente','ja':'充電器/電源アダプタ','ko':'충전기/전원 어댑터','pt':'Carregador/adaptador de energia','ar':'شاحن/محول طاقة'},
  'xb.hs.hoodie': {'zh':'卫衣/帽衫','en':'Hoodie/sweatshirt','de':'Hoodie/Sweatshirt','fr':'Sweat à capuche','es':'Sudadera/capucha','ja':'パーカー/スウェット','ko':'후디/스웨트셔츠','pt':'Moletom/capuz','ar':'هودي/بلوزة رياضية'},
  # prohibited
  'xb.proh.US.banned': {'zh':'武器弹药、毒品、象牙制品、古巴雪茄、盗版商品、未批准药品、肉类乳制品','en':'Weapons, drugs, ivory products, Cuban cigars, counterfeit goods, unapproved pharmaceuticals, meat/dairy','de':'Waffen, Drogen, Elfenbeinprodukte, kubanische Zigarren, Fälschungen, nicht zugelassene Arzneimittel, Fleisch/Milchprodukte','fr':'Armes, drogues, ivoire, cigares cubains, contrefaçons, médicaments non approuvés, viande/produits laitiers','es':'Armas, drogas, marfil, cigarros cubanos, falsificaciones, medicamentos no aprobados, carnes/lácteos','ja':'武器、麻薬、象牙製品、キューバ葉巻、偽造品、未承認医薬品、肉類/乳製品','ko':'무기, 마약, 상아 제품, 쿠바 시가, 위조품, 미승인 의약품, 육류/유제품','pt':'Armas, drogas, marfim, charutos cubanos, falsificações, medicamentos não aprovados, carne/laticínios','ar':'الأسلحة، المخدرات، منتجات العاج، سيجار كوبي، بضائع مقلدة، أدوية غير معتمدة، لحوم/منتجات الألبان'},
  'xb.proh.US.restricted': {'zh':'含酒精饮料、烟草产品、处方药(FDA)、电子产品(FCC)、儿童产品(CPSC)','en':"Alcoholic beverages, tobacco, prescription drugs (FDA), electronics (FCC), children's products (CPSC)",'de':'Alkoholische Getränke, Tabak, verschreibungspflichtige Medikamente (FDA), Elektronik (FCC), Kinderprodukte (CPSC)','fr':'Boissons alcoolisées, tabac, médicaments sur ordonnance (FDA), électroniques (FCC), produits pour enfants (CPSC)','es':'Bebidas alcohólicas, tabaco, medicamentos con receta (FDA), electrónicos (FCC), productos infantiles (CPSC)','ja':'アルコール飲料、たばこ、処方薬(FDA)、電子機器(FCC)、子供用製品(CPSC)','ko':'알코올 음료, 담배, 처방약(FDA), 전자제품(FCC), 아동 제품(CPSC)','pt':'Bebidas alcoólicas, tabaco, medicamentos prescritos (FDA), eletrônicos (FCC), produtos infantis (CPSC)','ar':'المشروبات الكحولية، التبغ، الأدوية الموصوفة (FDA)، الإلكترونيات (FCC)، منتجات الأطفال (CPSC)'},
  'xb.proh.US.deminimis': {'zh':'<strong>$800</strong> 以下免税（Section 321）','en':'Under <strong>$800</strong> duty-free (Section 321)','de':'Unter <strong>$800</strong> zollfrei (Section 321)','fr':'Moins de <strong>$800</strong> en franchise de droits (Section 321)','es':'Menos de <strong>$800</strong> libre de impuestos (Section 321)','ja':'<strong>$800</strong>以下は免税（Section 321）','ko':'<strong>$800</strong> 미만 면세 (Section 321)','pt':'Abaixo de <strong>$800</strong> isento (Section 321)','ar':'أقل من <strong>$800</strong> معفى من الضرائب (Section 321)'},
  'xb.proh.GB.banned': {'zh':'武器、毒品、濒危动植物、未经UKCA认证无线设备、攻击性武器','en':'Weapons, drugs, endangered species, uncertified wireless devices (UKCA), offensive weapons','de':'Waffen, Drogen, geschützte Tiere/Pflanzen, nicht UKCA-zertifizierte Geräte, Angriffswaffen','fr':'Armes, drogues, espèces menacées, appareils sans certification UKCA, armes offensives','es':'Armas, drogas, especies en peligro, dispositivos sin certificación UKCA, armas ofensivas','ja':'武器、麻薬、絶滅危惧種、UKCA未認定無線機器、攻撃的武器','ko':'무기, 마약, 멸종위기종, UKCA 미인증 무선기기, 공격용 무기','pt':'Armas, drogas, espécies ameaçadas, dispositivos não certificados (UKCA), armas ofensivas','ar':'الأسلحة، المخدرات، الأنواع المهددة بالانقراض، الأجهزة اللاسلكية غير المعتمدة UKCA، الأسلحة الهجومية'},
  'xb.proh.GB.restricted': {'zh':'食品(卫生证书)、药品(MHRA)、含酒精饮料、烟草、动植物(检疫)','en':'Food (health certificate), pharmaceuticals (MHRA), alcoholic beverages, tobacco, animals/plants (quarantine)','de':'Lebensmittel (Gesundheitszeugnis), Arzneimittel (MHRA), alkoholische Getränke, Tabak, Tiere/Pflanzen (Quarantäne)','fr':'Aliments (certificat sanitaire), médicaments (MHRA), alcool, tabac, animaux/plantes (quarantaine)','es':'Alimentos (certificado sanitario), medicamentos (MHRA), alcohol, tabaco, animales/plantas (cuarentena)','ja':'食品(衛生証明書)、医薬品(MHRA)、アルコール飲料、たばこ、動植物(検疫)','ko':'식품(위생 증명서), 의약품(MHRA), 알코올 음료, 담배, 동식물(검역)','pt':'Alimentos (certificado sanitário), medicamentos (MHRA), álcool, tabaco, animais/plantas (quarentena)','ar':'الغذاء (شهادة صحية)، الأدوية (MHRA)، المشروبات الكحولية، التبغ، الحيوانات/النباتات (الحجر الصحي)'},
  'xb.proh.GB.deminimis': {'zh':'<strong>£135</strong> 以下免征关税，但均需缴VAT(20%)','en':'Under <strong>£135</strong> no customs duty, but VAT(20%) still applies','de':'Unter <strong>£135</strong> keine Zölle, aber MwSt.(20%) fällt an','fr':'Moins de <strong>£135</strong> sans droits de douane, mais TVA(20%) applicable','es':'Menos de <strong>£135</strong> sin aranceles, pero IVA(20%) aplica','ja':'<strong>£135</strong>以下は関税なし、ただしVAT(20%)は要','ko':'<strong>£135</strong> 미만 관세 면제, 단 VAT(20%) 부과','pt':'Abaixo de <strong>£135</strong> sem direitos alfandegários, mas IVA(20%) aplica','ar':'أقل من <strong>£135</strong> بدون رسوم جمركية، لكن VAT(20%) مطلوب'},
  'xb.proh.DE.banned': {'zh':'武器、毒品、纳粹物品、假冒商品、无CE标志电子产品、危险化学品','en':'Weapons, drugs, Nazi items, counterfeit goods, electronics without CE mark, hazardous chemicals','de':'Waffen, Drogen, Nazi-Gegenstände, Fälschungen, Elektronik ohne CE-Zeichen, Gefahrstoffe','fr':'Armes, drogues, articles nazis, contrefaçons, électroniques sans marquage CE, produits chimiques dangereux','es':'Armas, drogas, artículos nazis, falsificaciones, electrónicos sin marca CE, químicos peligrosos','ja':'武器、麻薬、ナチス関連品、偽造品、CEマーク無し電子機器、危険化学品','ko':'무기, 마약, 나치 물품, 위조품, CE 마크 없는 전자제품, 위험 화학물질','pt':'Armas, drogas, itens nazistas, falsificações, eletrônicos sem marca CE, químicos perigosos','ar':'الأسلحة، المخدرات، مواد النازية، البضائع المقلدة، الإلكترونيات بدون علامة CE، المواد الكيميائية الخطرة'},
  'xb.proh.DE.restricted': {'zh':'食品(欧盟卫生证书)、药品(EMA)、动植物(检疫)、无线设备(CE/RED)、化妆品(CPNP)','en':'Food (EU health cert), pharmaceuticals (EMA), animals/plants (quarantine), wireless devices (CE/RED), cosmetics (CPNP)','de':'Lebensmittel (EU-Gesundheitszeugnis), Arzneimittel (EMA), Tiere/Pflanzen (Quarantäne), Funkanlagen (CE/RED), Kosmetik (CPNP)','fr':'Aliments (cert. sanitaire UE), médicaments (EMA), animaux/plantes (quarantaine), appareils radio (CE/RED), cosmétiques (CPNP)','es':'Alimentos (cert. sanitario UE), medicamentos (EMA), animales/plantas (cuarentena), equipos radio (CE/RED), cosméticos (CPNP)','ja':'食品(EU衛生証明書)、医薬品(EMA)、動植物(検疫)、無線機器(CE/RED)、化粧品(CPNP)','ko':'식품(EU 위생 증명서), 의약품(EMA), 동식물(검역), 무선기기(CE/RED), 화장품(CPNP)','pt':'Alimentos (cert. sanitário UE), medicamentos (EMA), animais/plantas (quarentena), dispositivos sem fio (CE/RED), cosméticos (CPNP)','ar':'الغذاء (شهادة صحية EU)، الأدوية (EMA)، الحيوانات/النباتات (حجر صحي)، الأجهزة اللاسلكية (CE/RED)، مستحضرات التجميل (CPNP)'},
  'xb.proh.DE.deminimis': {'zh':'<strong>€0</strong> 起征 — 所有进口均需缴税。注意EPR合规。','en':'<strong>€0</strong> threshold — all imports taxed. Note EPR compliance.','de':'<strong>€0</strong> Schwelle — alle Importe werden besteuert. EPR-Konformität beachten.','fr':'Seuil <strong>€0</strong> — tous les imports sont taxés. Attention conformité EPR.','es':'Umbral <strong>€0</strong> — todas las importaciones tributan. Atención cumplimiento EPR.','ja':'<strong>€0</strong>以上全額課税。EPR準拠に注意。','ko':'<strong>€0</strong> 기준 — 모든 수입품 과세. EPR 준수 주의.','pt':'Limite <strong>€0</strong> — todas as importações tributadas. Atenção à conformidade EPR.','ar':'عتبة <strong>€0</strong> — جميع الواردات خاضعة للضريبة. انتبه لامتثال EPR.'},
  'xb.proh.JP.banned': {'zh':'武器、毒品、淫秽物品、假冒商品、侵权商品、含伪麻黄碱药品','en':'Weapons, drugs, obscene materials, counterfeit goods, infringing goods, pseudoephedrine-containing drugs','de':'Waffen, Drogen, obszöne Materialien, Fälschungen, rechtsverletzende Waren, Pseudoephedrin-Medikamente','fr':'Armes, drogues, matériaux obscènes, contrefaçons, marchandises en infraction, médicaments à la pseudoéphédrine','es':'Armas, drogas, materiales obscenos, falsificaciones, mercancías infractoras, medicamentos con pseudoefedrina','ja':'武器、麻薬、わいせつ物、偽造品、侵害品、プソイドエフェドリン含有薬','ko':'무기, 마약, 음란물, 위조품, 침해 상품, 슈도에페드린 함유 약품','pt':'Armas, drogas, materiais obscenos, falsificações, mercadorias infratoras, medicamentos com pseudoefedrina','ar':'الأسلحة، المخدرات، المواد الإباحية، البضائع المقلدة، البضائع المنتهكة، أدوية الإيفيدرين الكاذب'},
  'xb.proh.JP.restricted': {'zh':'食品(检疫)、化妆品(药事法)、电子产品(PSE/TELEC)、动植物(严格检疫)','en':'Food (quarantine), cosmetics (Pharmaceutical Affairs Law), electronics (PSE/TELEC), animals/plants (strict quarantine)','de':'Lebensmittel (Quarantäne), Kosmetik (Arzneimittelgesetz), Elektronik (PSE/TELEC), Tiere/Pflanzen (strenge Quarantäne)','fr':'Aliments (quarantaine), cosmétiques (Loi pharmaceutique), électroniques (PSE/TELEC), animaux/plantes (quarantaine stricte)','es':'Alimentos (cuarentena), cosméticos (Ley Farmacéutica), electrónicos (PSE/TELEC), animales/plantas (cuarentena estricta)','ja':'食品(検疫)、化粧品(薬事法)、電子機器(PSE/TELEC)、動植物(厳格検疫)','ko':'식품(검역), 화장품(약사법), 전자제품(PSE/TELEC), 동식물(엄격 검역)','pt':'Alimentos (quarentena), cosméticos (Lei Farmacêutica), eletrônicos (PSE/TELEC), animais/plantas (quarentena rigorosa)','ar':'الغذاء (حجر صحي)، مستحضرات التجميل (قانون الصيدلة)، الإلكترونيات (PSE/TELEC)، الحيوانات/النباتات (حجر صحي صارم)'},
  'xb.proh.JP.deminimis': {'zh':'<strong>¥10,000</strong> 以下免税','en':'Under <strong>¥10,000</strong> duty-free','de':'Unter <strong>¥10.000</strong> zollfrei','fr':'Moins de <strong>¥10 000</strong> en franchise','es':'Menos de <strong>¥10,000</strong> libre de impuestos','ja':'<strong>¥10,000</strong>以下免税','ko':'<strong>¥10,000</strong> 미만 면세','pt':'Abaixo de <strong>¥10.000</strong> isento','ar':'أقل من <strong>¥10,000</strong> معفى من الضرائب'},
  'xb.proh.AU.banned': {'zh':'武器、毒品、石棉制品、未经批准转基因产品','en':'Weapons, drugs, asbestos products, unapproved GMO products','de':'Waffen, Drogen, Asbestprodukte, nicht genehmigte GVO-Produkte','fr':'Armes, drogues, produits en amiante, produits OGM non approuvés','es':'Armas, drogas, productos de asbesto, productos OGM no aprobados','ja':'武器、麻薬、石綿製品、未承認GMO製品','ko':'무기, 마약, 석면 제품, 미승인 GMO 제품','pt':'Armas, drogas, produtos de amianto, produtos OGM não aprovados','ar':'الأسلحة، المخدرات، منتجات الأسبستوس، منتجات GMO غير معتمدة'},
  'xb.proh.AU.restricted': {'zh':'食品(严格检疫)、药品(TGA)、动植物制品(检疫)、无线设备(ACMA)','en':'Food (strict quarantine), pharmaceuticals (TGA), animal/plant products (quarantine), wireless devices (ACMA)','de':'Lebensmittel (strenge Quarantäne), Arzneimittel (TGA), Tier-/Pflanzenprod. (Quarantäne), Funkanlagen (ACMA)','fr':'Aliments (quarantaine stricte), médicaments (TGA), produits animaux/végétaux (quarantaine), appareils radio (ACMA)','es':'Alimentos (cuarentena estricta), medicamentos (TGA), productos animales/vegetales (cuarentena), equipos radio (ACMA)','ja':'食品(厳格検疫)、医薬品(TGA)、動植物製品(検疫)、無線機器(ACMA)','ko':'식품(엄격 검역), 의약품(TGA), 동식물 제품(검역), 무선기기(ACMA)','pt':'Alimentos (quarentena rigorosa), medicamentos (TGA), produtos animais/vegetais (quarentena), dispositivos sem fio (ACMA)','ar':'الغذاء (حجر صحي صارم)، الأدوية (TGA)، منتجات الحيوانات/النباتات (حجر صحي)، الأجهزة اللاسلكية (ACMA)'},
  'xb.proh.AU.deminimis': {'zh':'<strong>A$1,000</strong> 以下免税','en':'Under <strong>A$1,000</strong> duty-free','de':'Unter <strong>A$1.000</strong> zollfrei','fr':'Moins de <strong>A$1 000</strong> en franchise','es':'Menos de <strong>A$1,000</strong> libre de impuestos','ja':'<strong>A$1,000</strong>以下免税','ko':'<strong>A$1,000</strong> 미만 면세','pt':'Abaixo de <strong>A$1.000</strong> isento','ar':'أقل من <strong>A$1,000</strong> معفى من الضرائب'},
  'xb.proh.CA.banned': {'zh':'武器、毒品、淫秽物品、仇恨言论材料、未申报食品','en':'Weapons, drugs, obscene materials, hate speech materials, undeclared food','de':'Waffen, Drogen, obszöne Materialien, Hassmaterial, nicht deklarierte Lebensmittel','fr':'Armes, drogues, matériaux obscènes, discours haineux, aliments non déclarés','es':'Armas, drogas, materiales obscenos, discurso de odio, alimentos no declarados','ja':'武器、麻薬、わいせつ物、ヘイトスピーチ材料、未申告食品','ko':'무기, 마약, 음란물, 혐오 발언 자료, 미신고 식품','pt':'Armas, drogas, materiais obscenos, discurso de ódio, alimentos não declarados','ar':'الأسلحة، المخدرات، المواد الإباحية، مواد خطاب الكراهية، الأغذية غير المعلنة'},
  'xb.proh.CA.restricted': {'zh':'食品(CFIA)、药品(Health Canada)、无线设备(ISED)、动植物(检疫)','en':'Food (CFIA), pharmaceuticals (Health Canada), wireless devices (ISED), animals/plants (quarantine)','de':'Lebensmittel (CFIA), Arzneimittel (Health Canada), Funkanlagen (ISED), Tiere/Pflanzen (Quarantäne)','fr':'Aliments (CFIA), médicaments (Santé Canada), appareils radio (ISED), animaux/plantes (quarantaine)','es':'Alimentos (CFIA), medicamentos (Health Canada), equipos radio (ISED), animales/plantas (cuarentena)','ja':'食品(CFIA)、医薬品(Health Canada)、無線機器(ISED)、動植物(検疫)','ko':'식품(CFIA), 의약품(Health Canada), 무선기기(ISED), 동식물(검역)','pt':'Alimentos (CFIA), medicamentos (Health Canada), dispositivos sem fio (ISED), animais/plantas (quarentena)','ar':'الغذاء (CFIA)، الأدوية (Health Canada)، الأجهزة اللاسلكية (ISED)، الحيوانات/النباتات (حجر صحي)'},
  'xb.proh.CA.deminimis': {'zh':'<strong>C$20</strong> 起征（极低）','en':'<strong>C$20</strong> threshold (very low)','de':'<strong>C$20</strong> Schwelle (sehr niedrig)','fr':'Seuil <strong>C$20</strong> (très bas)','es':'Umbral <strong>C$20</strong> (muy bajo)','ja':'<strong>C$20</strong>以上課税（非常に低い）','ko':'<strong>C$20</strong> 기준 (매우 낮음)','pt':'Limite <strong>C$20</strong> (muito baixo)','ar':'عتبة <strong>C$20</strong> (منخفضة جداً)'},
  # dashboard/sidebar
  'xb.dash.empty_route': {'zh':'查询物流后，点击"收藏此路线"即可快速复用','en':'After querying, click "Save this route" for quick reuse','de':'Nach der Abfrage auf "Route speichern" klicken','fr':'Après recherche, cliquez sur "Sauvegarder" pour réutiliser','es':'Después de consultar, haga clic en "Guardar ruta" para reutilizar','ja':'物流照会後、「このルートを保存」をクリックして再利用','ko':'조회 후 "이 경로 저장"을 클릭하여 재사용','pt':'Após consulta, clique em "Salvar rota" para reutilizar','ar':'بعد الاستعلام، انقر على "حفظ هذا المسار" لإعادة الاستخدام'},
  'xb.dash.click_fill': {'zh':'点击一键填入','en':'Click to auto-fill','de':'Klicken zum automatischen Ausfüllen','fr':'Cliquez pour remplir automatiquement','es':'Haga clic para rellenar automáticamente','ja':'クリックして自動入力','ko':'클릭하여 자동 입력','pt':'Clique para preencher automaticamente','ar':'انقر للملء التلقائي'},
  'xb.dash.routes': {'zh':'条路线','en':' routes','de':' Routen','fr':' itinéraires','es':' rutas','ja':' ルート','ko':' 경로','pt':' rotas','ar':' مسارات'},
  'xb.dash.empty_track': {'zh':'追踪包裹后，点击"添加到关注列表"保存','en':'After tracking, click "Add to watchlist" to save','de':'Nach Verfolgung auf "Zur Beobachtungsliste" klicken','fr':'Après suivi, cliquez "Ajouter à la liste de suivi"','es':'Tras rastrear, haga clic en "Añadir a la lista" para guardar','ja':'追跡後、「ウォッチリストに追加」をクリックして保存','ko':'추적 후 "관심 목록에 추가"를 클릭하여 저장','pt':'Após rastrear, clique em "Adicionar à lista" para salvar','ar':'بعد التتبع، انقر على "إضافة إلى قائمة المراقبة" للحفظ'},
  'xb.dash.last_update': {'zh':'上次更新：','en':'Last updated: ','de':'Zuletzt aktualisiert: ','fr':'Dernière mise à jour : ','es':'Última actualización: ','ja':'最終更新：','ko':'최종 업데이트: ','pt':'Última atualização: ','ar':'آخر تحديث: '},
  'xb.dash.parcels': {'zh':'个包裹','en':' parcels','de':' Pakete','fr':' colis','es':' paquetes','ja':' 個の荷物','ko':' 소포','pt':' pacotes','ar':' طرود'},
  'xb.sidebar.no_routes': {'zh':'暂无收藏路线','en':'No saved routes','de':'Keine gespeicherten Routen','fr':'Aucun itinéraire sauvegardé','es':'No hay rutas guardadas','ja':'保存されたルートなし','ko':'저장된 경로 없음','pt':'Nenhuma rota salva','ar':'لا توجد مسارات محفوظة'},
  'xb.sidebar.no_tracks': {'zh':'暂无追踪包裹','en':'No tracked parcels','de':'Keine verfolgten Pakete','fr':'Aucun colis suivi','es':'No hay paquetes rastreados','ja':'追跡中の荷物なし','ko':'추적 중인 소포 없음','pt':'Nenhum pacote rastreado','ar':'لا توجد طرود متتبعة'},
  # toasts & buttons
  'xb.toast.route_updated': {'zh':'路线已更新！','en':'Route updated!','de':'Route aktualisiert!','fr':'Itinéraire mis à jour !','es':'¡Ruta actualizada!','ja':'ルートを更新しました！','ko':'경로가 업데이트되었습니다!','pt':'Rota atualizada!','ar':'تم تحديث المسار!'},
  'xb.toast.route_saved': {'zh':'路线已收藏！⭐','en':'Route saved! ⭐','de':'Route gespeichert! ⭐','fr':'Itinéraire sauvegardé ! ⭐','es':'¡Ruta guardada! ⭐','ja':'ルートを保存しました！⭐','ko':'경로가 저장되었습니다! ⭐','pt':'Rota salva! ⭐','ar':'تم حفظ المسار! ⭐'},
  'xb.toast.track_added': {'zh':'已添加到关注列表 📌','en':'Added to watchlist 📌','de':'Zur Beobachtungsliste hinzugefügt 📌','fr':'Ajouté à la liste de suivi 📌','es':'Añadido a la lista de seguimiento 📌','ja':'ウォッチリストに追加しました 📌','ko':'관심 목록에 추가되었습니다 📌','pt':'Adicionado à lista de acompanhamento 📌','ar':'تمت الإضافة إلى قائمة المراقبة 📌'},
  'xb.toast.enter_tn': {'zh':'请输入运单号','en':'Please enter a tracking number','de':'Bitte Sendungsnummer eingeben','fr':'Veuillez saisir un numéro de suivi','es':'Por favor ingrese un número de seguimiento','ja':'追跡番号を入力してください','ko':'운송장 번호를 입력하세요','pt':'Por favor, insira um número de rastreamento','ar':'يرجى إدخال رقم التتبع'},
  'xb.btn.saved': {'zh':'✅ 已收藏，下次一键调用','en':'✅ Saved, one-click next time','de':'✅ Gespeichert, nächstes Mal ein Klick','fr':'✅ Sauvegardé, un clic la prochaine fois','es':'✅ Guardado, un clic la próxima vez','ja':'✅ 保存済み、次回ワンクリック','ko':'✅ 저장됨, 다음번에 원클릭','pt':'✅ Salvo, um clique na próxima vez','ar':'✅ محفوظ، نقرة واحدة في المرة القادمة'},
  'xb.btn.save_route': {'zh':'📌 收藏此路线，下次一键调用','en':'📌 Save this route for one-click reuse','de':'📌 Route speichern für einen Klick','fr':'📌 Sauvegarder cet itinéraire','es':'📌 Guardar esta ruta para uso rápido','ja':'📌 このルートを保存してワンクリック再利用','ko':'📌 이 경로 저장하여 원클릭 재사용','pt':'📌 Salvar esta rota para reuso rápido','ar':'📌 حفظ هذا المسار لإعادة الاستخدام بنقرة'},
  # weekdays
  'xb.weekday.mon': {'zh':'周一','en':'Mon','de':'Mo','fr':'Lun','es':'Lun','ja':'月曜','ko':'월요일','pt':'Seg','ar':'الاثنين'},
  'xb.weekday.tue': {'zh':'周二','en':'Tue','de':'Di','fr':'Mar','es':'Mar','ja':'火曜','ko':'화요일','pt':'Ter','ar':'الثلاثاء'},
  'xb.weekday.wed': {'zh':'周三','en':'Wed','de':'Mi','fr':'Mer','es':'Mié','ja':'水曜','ko':'수요일','pt':'Qua','ar':'الأربعاء'},
  'xb.weekday.thu': {'zh':'周四','en':'Thu','de':'Do','fr':'Jeu','es':'Jue','ja':'木曜','ko':'목요일','pt':'Qui','ar':'الخميس'},
  'xb.weekday.fri': {'zh':'周五','en':'Fri','de':'Fr','fr':'Ven','es':'Vie','ja':'金曜','ko':'금요일','pt':'Sex','ar':'الجمعة'},
  'xb.weekday.sat': {'zh':'周六','en':'Sat','de':'Sa','fr':'Sam','es':'Sáb','ja':'土曜','ko':'토요일','pt':'Sáb','ar':'السبت'},
  'xb.weekday.sun': {'zh':'周日','en':'Sun','de':'So','fr':'Dim','es':'Dom','ja':'日曜','ko':'일요일','pt':'Dom','ar':'الأحد'},
  # ETA
  'xb.eta.working': {'zh':'派送员正在工作','en':'Delivery staff working','de':'Zustellpersonal arbeitet','fr':'Personnel de livraison en service','es':'Personal de entrega trabajando','ja':'配達スタッフ稼働中','ko':'배달 직원 근무 중','pt':'Equipe de entrega trabalhando','ar':'موظف التوصيل يعمل'},
  'xb.eta.weekend': {'zh':'周末到达，可能下周一才派送','en':'Weekend arrival, may deliver next Monday','de':'Ankunft am Wochenende, Zustellung evtl. erst Montag','fr':'Arrivée le week-end, livraison possible lundi','es':'Llegada en fin de semana, entrega posible el lunes','ja':'週末到着、月曜配達の可能性','ko':'주말 도착, 월요일에 배달 가능','pt':'Chegada no fim de semana, entrega possível na segunda','ar':'وصول في عطلة نهاية الأسبوع، قد يُسلَّم الاثنين'},
  'xb.eta.offhours': {'zh':'非工作时间到达，可能次日派送','en':'Off-hours arrival, may deliver next day','de':'Ankunft außerhalb der Geschäftszeiten, evtl. nächster Tag','fr':'Arrivée hors heures, livraison possible le lendemain','es':'Llegada fuera de horario, entrega posible al día siguiente','ja':'勤務時間外到着、翌日配達の可能性','ko':'비업무 시간 도착, 다음날 배달 가능','pt':'Chegada fora do horário, entrega possível no dia seguinte','ar':'الوصول خارج ساعات العمل، قد يُسلَّم في اليوم التالي'},
  'xb.eta.ontime': {'zh':'预计准时到达','en':'Expected on-time delivery','de':'Voraussichtlich pünktliche Lieferung','fr':'Livraison à temps prévue','es':'Entrega a tiempo esperada','ja':'予定通り到着予定','ko':'정시 배달 예정','pt':'Entrega pontual prevista','ar':'التسليم في الوقت المحدد متوقع'},
  # ship day
  'xb.ship.today_bad': {'zh':'⚠️ 今天发货','en':'⚠️ Ship today ','de':'⚠️ Heute versenden ','fr':"⚠️ Expédier aujourd'hui ",'es':'⚠️ Enviar hoy ','ja':'⚠️ 本日発送 ','ko':'⚠️ 오늘 발송 ','pt':'⚠️ Enviar hoje ','ar':'⚠️ الشحن اليوم '},
  'xb.ship.arrive_but': {'zh':'到，但','en':' arrives, but ','de':' kommt an, aber ','fr':' arrive, mais ','es':' llega, pero ','ja':' 到着、しかし ','ko':' 도착, 하지만 ','pt':' chega, mas ','ar':' يصل، لكن '},
  'xb.ship.delay_suggest': {'zh':'才派送。建议等一天。','en':' delivery. Suggest waiting a day.','de':' Zustellung. Warte lieber einen Tag.','fr':" livraison. Suggère d'attendre un jour.",'es':' entrega. Se sugiere esperar un día.','ja':' 配達。一日待つことを推奨。','ko':' 배달. 하루 기다리는 것을 권장.','pt':' entrega. Sugere esperar um dia.','ar':' التسليم. يُنصح بالانتظار يوماً.'},
  'xb.ship.today_ok': {'zh':'✅ 今天发货，预计','en':'✅ Ship today, expected ','de':'✅ Heute versenden, voraussichtlich ','fr':"✅ Expédier aujourd'hui, prévu ",'es':'✅ Enviar hoy, previsto ','ja':'✅ 本日発送、予定 ','ko':'✅ 오늘 발송, 예상 ','pt':'✅ Enviar hoje, previsto ','ar':'✅ الشحن اليوم، متوقع '},
  'xb.ship.arrive': {'zh':'到达','en':' arrival','de':' Ankunft','fr':' arrivée','es':' llegada','ja':' 到着','ko':' 도착','pt':' chegada','ar':' وصول'},
  'xb.ship.tomorrow': {'zh':'明天(','en':'Tomorrow (','de':'Morgen (','fr':'Demain (','es':'Mañana (','ja':'明日（','ko':'내일(','pt':'Amanhã (','ar':'غداً ('},
  'xb.ship.ship': {'zh':')发货','en':') ship','de':') versenden','fr':') expédier','es':') enviar','ja':') 発送','ko':') 발송','pt':') enviar','ar':') شحن'},
  'xb.ship.days_later': {'zh':'天后发货','en':' days later','de':' Tage später','fr':' jours plus tard','es':' días después','ja':' 日後発送','ko':' 일 후 발송','pt':' dias depois','ar':' أيام لاحقاً'},
  # countdown
  'xb.countdown.arrive': {'zh':'天后到达','en':' days to arrival','de':' Tage bis Ankunft','fr':' jours avant arrivée','es':' días para llegar','ja':' 日後到着','ko':' 일 후 도착','pt':' dias para chegada','ar':' أيام حتى الوصول'},
  # DDP
  'xb.ddp.exempt': {'zh':'低于免税起征点，无需缴税','en':'Below de minimis, no tax required','de':'Unter dem Schwellenwert, keine Steuer','fr':'En dessous du seuil, pas de taxe','es':'Por debajo del mínimo, sin impuestos','ja':'免税最低額以下、課税なし','ko':'최저 면세 기준 이하, 세금 없음','pt':'Abaixo do mínimo isento, sem impostos','ar':'دون الحد الأدنى، لا ضريبة مطلوبة'},
  'xb.ddp.estimate': {'zh':'基于平均税率估算，实际以海关核定为准。','en':'Estimated based on avg. rate; actual per customs.','de':'Schätzung nach Durchschnittssatz; tatsächlich nach Zollbehörde.','fr':'Estimation basée sur le taux moyen ; selon les douanes.','es':'Estimación basada en tasa promedio; según aduanas.','ja':'平均税率に基づく推定、実際は税関確定に従う。','ko':'평균 세율 기준 추정, 실제는 세관 결정에 따름.','pt':'Estimativa com base na taxa média; conforme alfândega.','ar':'تقدير بناءً على متوسط المعدل؛ الفعلي وفق الجمارك.'},
  # result labels
  'xb.result.empty': {'zh':'没有匹配的物流方案','en':'No matching logistics plans','de':'Keine passenden Logistikpläne','fr':'Aucun plan logistique correspondant','es':'No hay planes logísticos coincidentes','ja':'一致する物流プランなし','ko':'일치하는 물류 계획 없음','pt':'Nenhum plano logístico correspondente','ar':'لا توجد خطط لوجستية مطابقة'},
  'xb.type.express': {'zh':'快递','en':'Express','de':'Express','fr':'Express','es':'Express','ja':'速達','ko':'특급','pt':'Expresso','ar':'سريع'},
  'xb.type.air': {'zh':'空运','en':'Air','de':'Luftfracht','fr':'Aérien','es':'Aéreo','ja':'航空便','ko':'항공','pt':'Aéreo','ar':'جوي'},
  'xb.type.sea': {'zh':'海运','en':'Sea','de':'Seefracht','fr':'Maritime','es':'Marítimo','ja':'海運','ko':'해운','pt':'Marítimo','ar':'بحري'},
  'xb.badge.fastest': {'zh':'最快','en':'Fastest','de':'Schnellste','fr':'Le plus rapide','es':'Más rápido','ja':'最速','ko':'최단','pt':'Mais rápido','ar':'الأسرع'},
  'xb.badge.cheapest': {'zh':'最省','en':'Cheapest','de':'Günstigste','fr':'Le moins cher','es':'Más barato','ja':'最安','ko':'최저가','pt':'Mais barato','ar':'الأرخص'},
  'xb.result.ddp_total': {'zh':'含税总价(DDP)：','en':'Total incl. tax (DDP): ','de':'Gesamtpreis inkl. Steuer (DDP): ','fr':'Total TTC (DDP) : ','es':'Total incl. impuesto (DDP): ','ja':'税込総額(DDP)：','ko':'세금 포함 총액(DDP): ','pt':'Total incl. imposto (DDP): ','ar':'الإجمالي شامل الضريبة (DDP): '},
  'xb.result.duty': {'zh':'关税','en':'duty','de':'Zoll','fr':'droit de douane','es':'arancel','ja':'関税','ko':'관세','pt':'imposto','ar':'رسوم جمركية'},
  'xb.result.tax_free': {'zh':'免税 ✅','en':'Tax-free ✅','de':'Steuerfrei ✅','fr':'Exonéré ✅','es':'Libre de impuestos ✅','ja':'免税 ✅','ko':'면세 ✅','pt':'Isento ✅','ar':'معفى من الضريبة ✅'},
  'xb.result.local_time': {'zh':'当地时间','en':'local time','de':'Ortszeit','fr':'heure locale','es':'hora local','ja':'現地時間','ko':'현지 시간','pt':'hora local','ar':'التوقيت المحلي'},
  'xb.result.total_days': {'zh':'总时效：','en':'Total days: ','de':'Gesamttage: ','fr':'Jours totaux : ','es':'Total días: ','ja':'総日数：','ko':'총 소요일: ','pt':'Total de dias: ','ar':'إجمالي الأيام: '},
  'xb.result.days': {'zh':'天','en':'days','de':'Tage','fr':'jours','es':'días','ja':'日','ko':'일','pt':'dias','ar':'أيام'},
  'xb.result.transit': {'zh':'运输','en':'Transit ','de':'Transit ','fr':'Transit ','es':'Tránsito ','ja':'輸送 ','ko':'운송 ','pt':'Trânsito ','ar':'العبور '},
  'xb.result.days_unit': {'zh':'天','en':' days','de':' Tage','fr':' jours','es':' días','ja':' 日','ko':' 일','pt':' dias','ar':' أيام'},
  'xb.result.reliability': {'zh':'可靠性','en':'Reliability ','de':'Zuverlässigkeit ','fr':'Fiabilité ','es':'Fiabilidad ','ja':'信頼性 ','ko':'신뢰도 ','pt':'Confiabilidade ','ar':'الموثوقية '},
  'xb.result.eta': {'zh':'预计送达：','en':'Est. delivery: ','de':'Voraussichtliche Lieferung: ','fr':'Livraison prévue : ','es':'Entrega estimada: ','ja':'到着予定：','ko':'예상 배송: ','pt':'Entrega estimada: ','ar':'التسليم المتوقع: '},
  'xb.result.bill_weight': {'zh':'计费重','en':'Billed weight','de':'Berechnungsgewicht','fr':'Poids facturé','es':'Peso facturado','ja':'請求重量','ko':'청구 중량','pt':'Peso faturado','ar':'الوزن المحاسب'},
  # tariff
  'xb.tariff.goods_value': {'zh':'商品价值','en':'Goods value','de':'Warenwert','fr':'Valeur des marchandises','es':'Valor de bienes','ja':'商品価値','ko':'상품 가치','pt':'Valor das mercadorias','ar':'قيمة البضائع'},
  'xb.tariff.freight': {'zh':'国际运费','en':'International freight','de':'Internationale Fracht','fr':'Fret international','es':'Flete internacional','ja':'国際送料','ko':'국제 운임','pt':'Frete internacional','ar':'الشحن الدولي'},
  'xb.tariff.duty': {'zh':'关税','en':'Duty','de':'Zoll','fr':'Droits de douane','es':'Arancel','ja':'関税','ko':'관세','pt':'Imposto aduaneiro','ar':'رسوم جمركية'},
  'xb.tariff.vat': {'zh':'增值税VAT','en':'VAT','de':'Mehrwertsteuer (MwSt.)','fr':'TVA','es':'IVA','ja':'付加価値税(VAT)','ko':'부가가치세(VAT)','pt':'IVA','ar':'ضريبة القيمة المضافة (VAT)'},
  'xb.tariff.ddp_total': {'zh':'DDP到门总费用','en':'DDP total door cost','de':'DDP Gesamtkosten bis Tür','fr':'Coût total DDP porte à porte','es':'Costo total DDP puerta','ja':'DDP到着総費用','ko':'DDP 총 도어 비용','pt':'Custo total DDP porta','ar':'إجمالي تكلفة DDP للباب'},
  'xb.tariff.total_cost': {'zh':'含商品总成本','en':'Total incl. goods','de':'Gesamt inkl. Waren','fr':'Total marchandises incluses','es':'Total incl. mercancías','ja':'商品込み総コスト','ko':'상품 포함 총 비용','pt':'Total incl. mercadorias','ar':'الإجمالي شامل البضائع'},
  'xb.tariff.dest': {'zh':'目的地：','en':'Destination: ','de':'Ziel: ','fr':'Destination : ','es':'Destino: ','ja':'目的地：','ko':'목적지: ','pt':'Destino: ','ar':'الوجهة: '},
  'xb.tariff.category': {'zh':'商品类别：','en':'Category: ','de':'Kategorie: ','fr':'Catégorie : ','es':'Categoría: ','ja':'商品カテゴリ：','ko':'카테고리: ','pt':'Categoria: ','ar':'الفئة: '},
  'xb.tariff.exempt': {'zh':'✅ 低于免税起征点，无需缴关税和VAT！','en':'✅ Below de minimis, no duty or VAT!','de':'✅ Unter dem Schwellenwert, keine Zölle oder MwSt.!','fr':'✅ En dessous du seuil, pas de droits ni TVA !','es':'✅ Por debajo del mínimo, ¡sin aranceles ni IVA!','ja':'✅ 免税最低額以下、関税もVATも不要！','ko':'✅ 최저 면세 기준 이하, 관세 및 VAT 없음!','pt':'✅ Abaixo do mínimo isento, sem impostos ou IVA!','ar':'✅ دون الحد الأدنى، لا رسوم جمركية ولا VAT!'},
  # categories
  'xb.cat.electronics': {'zh':'电子产品/配件','en':'Electronics/accessories','de':'Elektronik/Zubehör','fr':'Électronique/accessoires','es':'Electrónica/accesorios','ja':'電子製品/アクセサリ','ko':'전자제품/액세서리','pt':'Eletrônicos/acessórios','ar':'إلكترونيات/ملحقات'},
  'xb.cat.clothing': {'zh':'服装/纺织品','en':'Clothing/textiles','de':'Kleidung/Textilien','fr':'Vêtements/textiles','es':'Ropa/textiles','ja':'衣類/繊維製品','ko':'의류/섬유','pt':'Roupas/têxteis','ar':'ملابس/منسوجات'},
  'xb.cat.toys': {'zh':'玩具/家居','en':'Toys/home goods','de':'Spielzeug/Haushalt','fr':'Jouets/articles ménagers','es':'Juguetes/hogar','ja':'おもちゃ/ホーム','ko':'장난감/홈용품','pt':'Brinquedos/artigos domésticos','ar':'ألعاب/منتجات منزلية'},
  'xb.cat.beauty': {'zh':'美妆/个护','en':'Beauty/personal care','de':'Beauty/Körperpflege','fr':'Beauté/soins personnels','es':'Belleza/cuidado personal','ja':'ビューティ/パーソナルケア','ko':'뷰티/퍼스널 케어','pt':'Beleza/cuidados pessoais','ar':'الجمال/العناية الشخصية'},
  'xb.cat.shoes': {'zh':'鞋靴/箱包','en':'Shoes/bags','de':'Schuhe/Taschen','fr':'Chaussures/sacs','es':'Zapatos/bolsos','ja':'靴/バッグ','ko':'신발/가방','pt':'Sapatos/bolsas','ar':'أحذية/حقائب'},
  'xb.cat.jewelry': {'zh':'珠宝/饰品','en':'Jewelry/accessories','de':'Schmuck/Accessoires','fr':'Bijoux/accessoires','es':'Joyería/accesorios','ja':'ジュエリー/アクセサリ','ko':'주얼리/액세서리','pt':'Joias/acessórios','ar':'مجوهرات/إكسسوارات'},
  'xb.cat.sports': {'zh':'运动/户外','en':'Sports/outdoor','de':'Sport/Outdoor','fr':'Sport/plein air','es':'Deportes/exterior','ja':'スポーツ/アウトドア','ko':'스포츠/아웃도어','pt':'Esportes/exterior','ar':'الرياضة/الهواء الطلق'},
  'xb.cat.auto': {'zh':'汽车配件','en':'Auto parts','de':'Autoteile','fr':'Pièces automobiles','es':'Repuestos de automóvil','ja':'自動車部品','ko':'자동차 부품','pt':'Peças automotivas','ar':'قطع غيار السيارات'},
  # countries
  'xb.cty.US': {'zh':'美国','en':'United States','de':'USA','fr':'États-Unis','es':'Estados Unidos','ja':'アメリカ','ko':'미국','pt':'Estados Unidos','ar':'الولايات المتحدة'},
  'xb.cty.GB': {'zh':'英国','en':'United Kingdom','de':'Großbritannien','fr':'Royaume-Uni','es':'Reino Unido','ja':'イギリス','ko':'영국','pt':'Reino Unido','ar':'المملكة المتحدة'},
  'xb.cty.DE': {'zh':'德国/欧盟','en':'Germany/EU','de':'Deutschland/EU','fr':'Allemagne/UE','es':'Alemania/UE','ja':'ドイツ/EU','ko':'독일/EU','pt':'Alemanha/UE','ar':'ألمانيا/الاتحاد الأوروبي'},
  'xb.cty.FR': {'zh':'法国/欧盟','en':'France/EU','de':'Frankreich/EU','fr':'France/UE','es':'Francia/UE','ja':'フランス/EU','ko':'프랑스/EU','pt':'França/UE','ar':'فرنسا/الاتحاد الأوروبي'},
  'xb.cty.JP': {'zh':'日本','en':'Japan','de':'Japan','fr':'Japon','es':'Japón','ja':'日本','ko':'일본','pt':'Japão','ar':'اليابان'},
  'xb.cty.AU': {'zh':'澳大利亚','en':'Australia','de':'Australien','fr':'Australie','es':'Australia','ja':'オーストラリア','ko':'호주','pt':'Austrália','ar':'أستراليا'},
  'xb.cty.CA': {'zh':'加拿大','en':'Canada','de':'Kanada','fr':'Canada','es':'Canadá','ja':'カナダ','ko':'캐나다','pt':'Canadá','ar':'كندا'},
  # tracking
  'xb.track.picked_up': {'zh':'已揽收','en':'Picked up','de':'Abgeholt','fr':'Collecté','es':'Recogido','ja':'集荷済み','ko':'픽업 완료','pt':'Coletado','ar':'تم الاستلام'},
  'xb.track.transit': {'zh':'运输中','en':'In transit','de':'Im Transit','fr':'En transit','es':'En tránsito','ja':'輸送中','ko':'운송 중','pt':'Em trânsito','ar':'في العبور'},
  'xb.track.customs': {'zh':'清关中','en':'Customs clearance','de':'In Zollabfertigung','fr':'En dédouanement','es':'En aduana','ja':'通関中','ko':'통관 중','pt':'Em alfândega','ar':'في الجمارك'},
  'xb.track.delivered': {'zh':'已签收','en':'Delivered','de':'Zugestellt','fr':'Livré','es':'Entregado','ja':'配達済み','ko':'배달 완료','pt':'Entregue','ar':'تم التسليم'},
  'xb.tl.picked_up': {'zh':'包裹已揽收，发往分拨中心','en':'Package picked up, heading to sorting center','de':'Paket abgeholt, auf dem Weg zum Sortierzentrum','fr':'Colis collecté, en route vers le centre de tri','es':'Paquete recogido, camino al centro de clasificación','ja':'荷物を集荷、仕分けセンターへ向かう','ko':'패키지 픽업, 분류 센터로 이동 중','pt':'Pacote coletado, a caminho do centro de triagem','ar':'تم استلام الطرد، في طريقه إلى مركز الفرز'},
  'xb.tl.left_sz': {'zh':'离开深圳分拨中心，发往目的地','en':'Left Shenzhen sorting center, heading to destination','de':'Shenzhen Sortierzentrum verlassen, Richtung Ziel','fr':'Quitté le centre de tri de Shenzhen, en route vers la destination','es':'Salió del centro de clasificación de Shenzhen, rumbo al destino','ja':'深圳仕分けセンターを出発、目的地へ向かう','ko':'선전 분류 센터 출발, 목적지로 향하는 중','pt':'Saiu do centro de triagem de Shenzhen, a caminho do destino','ar':'غادر مركز فرز شنتشن، في طريقه إلى الوجهة'},
  'xb.tl.arrived': {'zh':'已抵达目的地国家，等待清关','en':'Arrived at destination country, awaiting customs','de':'Im Zielland angekommen, wartet auf Zollabfertigung','fr':'Arrivé dans le pays de destination, en attente de dédouanement','es':'Llegó al país de destino, esperando aduana','ja':'目的地国に到着、通関待ち','ko':'목적지 국가 도착, 통관 대기 중','pt':'Chegou ao país de destino, aguardando alfândega','ar':'وصل إلى البلد المقصود، في انتظار الجمارك'},
  'xb.tl.cleared': {'zh':'清关完成，转交当地派送','en':'Customs cleared, handed to local delivery','de':'Zoll freigegeben, an lokale Zustellung übergeben','fr':'Dédouanement terminé, remis à la livraison locale','es':'Aduana liberada, entregado a mensajería local','ja':'通関完了、地元配送へ引き渡し','ko':'통관 완료, 현지 배달로 인계','pt':'Alfândega liberada, entregue à entrega local','ar':'الجمارك أُفرجت، تسليم إلى خدمة التوصيل المحلية'},
  'xb.tl.current': {'zh':'当前状态 — ','en':'Current status: ','de':'Aktueller Status: ','fr':'Statut actuel : ','es':'Estado actual: ','ja':'現在の状態 — ','ko':'현재 상태: ','pt':'Status atual: ','ar':'الحالة الحالية: '},
  'xb.loc.shenzhen': {'zh':'深圳','en':'Shenzhen','de':'Shenzhen','fr':'Shenzhen','es':'Shenzhen','ja':'深圳','ko':'선전','pt':'Shenzhen','ar':'شنتشن'},
  'xb.loc.sz_airport': {'zh':'深圳机场','en':'Shenzhen Airport','de':'Flughafen Shenzhen','fr':'Aéroport de Shenzhen','es':'Aeropuerto de Shenzhen','ja':'深圳空港','ko':'선전 공항','pt':'Aeroporto de Shenzhen','ar':'مطار شنتشن'},
  'xb.loc.destination': {'zh':'目的地','en':'Destination','de':'Zielort','fr':'Destination','es':'Destino','ja':'目的地','ko':'목적지','pt':'Destino','ar':'الوجهة'},
  'xb.loc.delivery': {'zh':'派送站','en':'Delivery center','de':'Zustellzentrum','fr':'Centre de livraison','es':'Centro de entrega','ja':'配送センター','ko':'배달 센터','pt':'Centro de entrega','ar':'مركز التوصيل'},
  # volume
  'xb.vol.volume': {'zh':'体积：','en':'Volume: ','de':'Volumen: ','fr':'Volume : ','es':'Volumen: ','ja':'体積：','ko':'부피: ','pt':'Volume: ','ar':'الحجم: '},
  'xb.vol.weight': {'zh':'体积重：','en':'Volumetric weight: ','de':'Volumengewicht: ','fr':'Poids volumétrique : ','es':'Peso volumétrico: ','ja':'容積重量：','ko':'체적 중량: ','pt':'Peso volumétrico: ','ar':'الوزن الحجمي: '},
  # destination label
  'xb.dest_label': {'zh':'目的地','en':'Destination','de':'Ziel','fr':'Destination','es':'Destino','ja':'目的地','ko':'목적지','pt':'Destino','ar':'الوجهة'},
}

langs = ['zh', 'en', 'de', 'fr', 'es', 'ja', 'ko', 'pt', 'ar']

for lang in langs:
    path = os.path.join(locales_dir, f'{lang}.json')
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    new_added = 0
    for key, translations in xb_keys.items():
        if key not in data:
            data[key] = translations.get(lang, translations.get('zh', key))
            new_added += 1

    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    xb_count = sum(1 for k in data if k.startswith('xb.'))
    print(f'{lang}.json: +{new_added} new keys  (xb.* total: {xb_count})')

print('\nAll done!')
